const diakritika = [
  {
    Name: "Jina Adamikov-Pelcov",
    Edit: "Jiřina Pelcová (Adamičková)",
    Sport: "Biathlon",
  },
  {
    Name: "Jina Adamikov-Pelcov",
    Edit: "Jiřina Pelcová (Adamičková)",
    Sport: "Biathlon",
  },
  {
    Name: "Jina Adamikov-Pelcov",
    Edit: "Jiřina Pelcová (Adamičková)",
    Sport: "Biathlon",
  },
  {
    Name: "Jina Adamikov-Pelcov",
    Edit: "Jiřina Pelcová (Adamičková)",
    Sport: "Biathlon",
  },
  {
    Name: "Jina Adamikov-Pelcov",
    Edit: "Jiřina Pelcová (Adamičková)",
    Sport: "Biathlon",
  },
  {
    Name: "Jina Adamikov-Pelcov",
    Edit: "Jiřina Pelcová (Adamičková)",
    Sport: "Biathlon",
  },
  { Name: "Jan Alin", Edit: "Jan Alinč", Sport: "Ice Hockey" },
  { Name: "David Bake", Edit: "David Bakeš", Sport: "Snowboarding" },
  { Name: "David Bake", Edit: "David Bakeš", Sport: "Snowboarding" },
  {
    Name: "Helena Balatkov-Erbenov",
    Edit: "Helena Erbenová (Balatková)",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Helena Balatkov-Erbenov",
    Edit: "Helena Erbenová (Balatková)",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Helena Balatkov-Erbenov",
    Edit: "Helena Erbenová (Balatková)",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Helena Balatkov-Erbenov",
    Edit: "Helena Erbenová (Balatková)",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Helena Balatkov-Erbenov",
    Edit: "Helena Erbenová (Balatková)",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Helena Balatkov-Erbenov",
    Edit: "Helena Erbenová (Balatková)",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Helena Balatkov-Erbenov",
    Edit: "Helena Erbenová (Balatková)",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Helena Balatkov-Erbenov",
    Edit: "Helena Erbenová (Balatková)",
    Sport: "Cross Country Skiing",
  },
  { Name: "Ondej Bank", Edit: "Ondřej Bank", Sport: "Alpine Skiing" },
  { Name: "Ondej Bank", Edit: "Ondřej Bank", Sport: "Alpine Skiing" },
  { Name: "Ondej Bank", Edit: "Ondřej Bank", Sport: "Alpine Skiing" },
  { Name: "Ondej Bank", Edit: "Ondřej Bank", Sport: "Alpine Skiing" },
  { Name: "Ondej Bank", Edit: "Ondřej Bank", Sport: "Alpine Skiing" },
  { Name: "Ondej Bank", Edit: "Ondřej Bank", Sport: "Alpine Skiing" },
  { Name: "Ondej Bank", Edit: "Ondřej Bank", Sport: "Alpine Skiing" },
  { Name: "Ondej Bank", Edit: "Ondřej Bank", Sport: "Alpine Skiing" },
  { Name: "Ondej Bank", Edit: "Ondřej Bank", Sport: "Alpine Skiing" },
  { Name: "Ondej Bank", Edit: "Ondřej Bank", Sport: "Alpine Skiing" },
  { Name: "Ondej Bank", Edit: "Ondřej Bank", Sport: "Alpine Skiing" },
  { Name: "Ondej Bank", Edit: "Ondřej Bank", Sport: "Alpine Skiing" },
  { Name: "Ondej Bank", Edit: "Ondřej Bank", Sport: "Alpine Skiing" },
  { Name: "Ondej Bank", Edit: "Ondřej Bank", Sport: "Alpine Skiing" },
  { Name: "Ondej Bank", Edit: "Ondřej Bank", Sport: "Alpine Skiing" },
  { Name: "Ondej Bank", Edit: "Ondřej Bank", Sport: "Alpine Skiing" },
  { Name: "Michal Barinka", Edit: "Michal Barinka", Sport: "Ice Hockey" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Luk Bauer", Edit: "Lukáš Bauer", Sport: "Cross Country Skiing" },
  { Name: "Pavel Benc", Edit: "Pavel Benc", Sport: "Cross Country Skiing" },
  { Name: "Pavel Benc", Edit: "Pavel Benc", Sport: "Cross Country Skiing" },
  { Name: "Pavel Benc", Edit: "Pavel Benc", Sport: "Cross Country Skiing" },
  { Name: "Pavel Benc", Edit: "Pavel Benc", Sport: "Cross Country Skiing" },
  { Name: "Josef Bernek", Edit: "Josef Beránek", Sport: "Ice Hockey" },
  {
    Name: "Kateina Bernkov",
    Edit: "Kateřina Beránková",
    Sport: "Figure Skating",
  },
  {
    Name: "Kateina Bernkov",
    Edit: "Kateřina Beránková",
    Sport: "Figure Skating",
  },
  { Name: "Miroslav Blat'k", Edit: "Miroslav Blaťák", Sport: "Ice Hockey" },
  { Name: "Martin Bohman", Edit: "Martin Bohman", Sport: "Bobsleigh" },
  { Name: "Michal Bezina", Edit: "Michal Březina", Sport: "Figure Skating" },
  { Name: "Michal Bezina", Edit: "Michal Březina", Sport: "Figure Skating" },
  { Name: "Petr Bza", Edit: "Petr Bříza", Sport: "Ice Hockey" },
  { Name: "Antonn Bro", Edit: "Antonín Brož", Sport: "Luge" },
  { Name: "Antonn Bro", Edit: "Antonín Brož", Sport: "Luge" },
  { Name: "Antonn Bro", Edit: "Antonín Brož", Sport: "Luge" },
  { Name: "Luk Bro", Edit: "Lukáš Brož", Sport: "Luge" },
  { Name: "Luk Bro", Edit: "Lukáš Brož", Sport: "Luge" },
  { Name: "Luk Bro", Edit: "Lukáš Brož", Sport: "Luge" },
  { Name: "Milan Brz", Edit: "Milan Brzý", Sport: "Figure Skating" },
  {
    Name: "Ilona Bublov",
    Edit: "Ilona Bublová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Ilona Bublov",
    Edit: "Ilona Bublová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Ilona Bublov",
    Edit: "Ilona Bublová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Lubomr Buchta",
    Edit: "Lubomír Buchta",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Lubomr Buchta",
    Edit: "Lubomír Buchta",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Lubomr Buchta",
    Edit: "Lubomír Buchta",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Lubomr Buchta",
    Edit: "Lubomír Buchta",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Lubomr Buchta",
    Edit: "Lubomír Buchta",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Lubomr Buchta",
    Edit: "Lubomír Buchta",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Lubomr Buchta",
    Edit: "Lubomír Buchta",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Lubomr Buchta",
    Edit: "Lubomír Buchta",
    Sport: "Cross Country Skiing",
  },
  { Name: "Jan Bulis", Edit: "Jan Bulis", Sport: "Ice Hockey" },
  { Name: "Petr ajnek", Edit: "Petr Čajánek", Sport: "Ice Hockey" },
  { Name: "Petr ajnek", Edit: "Petr Čajánek", Sport: "Ice Hockey" },
  { Name: "Petr ajnek", Edit: "Petr Čajánek", Sport: "Ice Hockey" },
  { Name: "Jan aloun", Edit: "Jan Čaloun", Sport: "Ice Hockey" },
  { Name: "Martin ernk", Edit: "Martin Černík", Sport: "Snowboarding" },
  { Name: "Roman ervenka", Edit: "Roman Červenka", Sport: "Ice Hockey" },
  { Name: "Roman ervenka", Edit: "Roman Červenka", Sport: "Ice Hockey" },
  { Name: "Patrik Chlum", Edit: "Patrik Chlum", Sport: "Nordic Combined" },
  {
    Name: "Radmila Chrobokov",
    Edit: "Radmila Chroboková",
    Sport: "Figure Skating",
  },
  {
    Name: "Lucie Chroustovsk",
    Edit: "Lucie Chroustovská",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Lucie Chroustovsk",
    Edit: "Lucie Chroustovská",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Lucie Chroustovsk",
    Edit: "Lucie Chroustovská",
    Sport: "Cross Country Skiing",
  },
  { Name: "Josef Chuchla", Edit: "Josef Chuchla", Sport: "Skeleton" },
  { Name: "Pavel Churav", Edit: "Pavel Churavý", Sport: "Nordic Combined" },
  { Name: "Pavel Churav", Edit: "Pavel Churavý", Sport: "Nordic Combined" },
  { Name: "Pavel Churav", Edit: "Pavel Churavý", Sport: "Nordic Combined" },
  { Name: "Pavel Churav", Edit: "Pavel Churavý", Sport: "Nordic Combined" },
  { Name: "Pavel Churav", Edit: "Pavel Churavý", Sport: "Nordic Combined" },
  { Name: "Pavel Churav", Edit: "Pavel Churavý", Sport: "Nordic Combined" },
  { Name: "Pavel Churav", Edit: "Pavel Churavý", Sport: "Nordic Combined" },
  { Name: "Pavel Churav", Edit: "Pavel Churavý", Sport: "Nordic Combined" },
  { Name: "Pavel Churav", Edit: "Pavel Churavý", Sport: "Nordic Combined" },
  { Name: "Pavel Churav", Edit: "Pavel Churavý", Sport: "Nordic Combined" },
  { Name: "Pavel Churav", Edit: "Pavel Churavý", Sport: "Nordic Combined" },
  { Name: "Pavel Churav", Edit: "Pavel Churavý", Sport: "Nordic Combined" },
  { Name: "Martin Cikl", Edit: "Martin Cikl", Sport: "Ski Jumping" },
  { Name: "Ivo Danilevi", Edit: "Ivo Danilevič", Sport: "Bobsleigh" },
  { Name: "Ivo Danilevi", Edit: "Ivo Danilevič", Sport: "Bobsleigh" },
  { Name: "Ivo Danilevi", Edit: "Ivo Danilevič", Sport: "Bobsleigh" },
  { Name: "Ivo Danilevi", Edit: "Ivo Danilevič", Sport: "Bobsleigh" },
  { Name: "Ivo Danilevi", Edit: "Ivo Danilevič", Sport: "Bobsleigh" },
  { Name: "Ivo Danilevi", Edit: "Ivo Danilevič", Sport: "Bobsleigh" },
  { Name: "Otto Dlabola", Edit: "Otto Dlabola", Sport: "Figure Skating" },
  { Name: "Otto Dlabola", Edit: "Otto Dlabola", Sport: "Figure Skating" },
  { Name: "Ladislav Dluho", Edit: "Ladislav Dluhoš", Sport: "Ski Jumping" },
  { Name: "Ladislav Dluho", Edit: "Ladislav Dluhoš", Sport: "Ski Jumping" },
  { Name: "Ladislav Dluho", Edit: "Ladislav Dluhoš", Sport: "Ski Jumping" },
  { Name: "Ji Doleal", Edit: "Jiří Doležal", Sport: "Ice Hockey" },
  { Name: "Michal Doleal", Edit: "Michal Doležal", Sport: "Ski Jumping" },
  { Name: "Michal Doleal", Edit: "Michal Doležal", Sport: "Ski Jumping" },
  { Name: "Michal Doleal", Edit: "Michal Doležal", Sport: "Ski Jumping" },
  { Name: "Michal Doleal", Edit: "Michal Doležal", Sport: "Ski Jumping" },
  { Name: "Michal Doleal", Edit: "Michal Doležal", Sport: "Ski Jumping" },
  { Name: "Michal Doleal", Edit: "Michal Doležal", Sport: "Ski Jumping" },
  { Name: "Zuzana Dolealov", Edit: "Zuzana Doležalová", Sport: "Snowboarding" },
  { Name: "Ji Dopita", Edit: "Jiří Dopita", Sport: "Ice Hockey" },
  { Name: "Ji Dopita", Edit: "Jiří Dopita", Sport: "Ice Hockey" },
  { Name: "Roman Dostl", Edit: "Roman Dostál", Sport: "Biathlon" },
  { Name: "Roman Dostl", Edit: "Roman Dostál", Sport: "Biathlon" },
  { Name: "Roman Dostl", Edit: "Roman Dostál", Sport: "Biathlon" },
  { Name: "Roman Dostl", Edit: "Roman Dostál", Sport: "Biathlon" },
  { Name: "Roman Dostl", Edit: "Roman Dostál", Sport: "Biathlon" },
  { Name: "Roman Dostl", Edit: "Roman Dostál", Sport: "Biathlon" },
  { Name: "Roman Dostl", Edit: "Roman Dostál", Sport: "Biathlon" },
  { Name: "Roman Dostl", Edit: "Roman Dostál", Sport: "Biathlon" },
  { Name: "Roman Dostl", Edit: "Roman Dostál", Sport: "Biathlon" },
  { Name: "Roman Dostl", Edit: "Roman Dostál", Sport: "Biathlon" },
  { Name: "Roman Dostl", Edit: "Roman Dostál", Sport: "Biathlon" },
  { Name: "Martina Dubovsk", Edit: "Martina Dubovská", Sport: "Alpine Skiing" },
  { Name: "Martina Dubovsk", Edit: "Martina Dubovská", Sport: "Alpine Skiing" },
  { Name: "Dominik Dvok", Edit: "Dominik Dvořák", Sport: "Bobsleigh" },
  { Name: "Miroslav Dvok", Edit: "Miroslav Dvořák", Sport: "Nordic Combined" },
  { Name: "Miroslav Dvok", Edit: "Miroslav Dvořák", Sport: "Nordic Combined" },
  { Name: "Miroslav Dvok", Edit: "Miroslav Dvořák", Sport: "Nordic Combined" },
  { Name: "Miroslav Dvok", Edit: "Miroslav Dvořák", Sport: "Nordic Combined" },
  { Name: "Miroslav Dvok", Edit: "Miroslav Dvořák", Sport: "Nordic Combined" },
  { Name: "Miroslav Dvok", Edit: "Miroslav Dvořák", Sport: "Nordic Combined" },
  { Name: "Radek Dvok", Edit: "Radek Dvořák", Sport: "Ice Hockey" },
  { Name: "Ji Dzmura", Edit: "Jiří Džmura", Sport: "Bobsleigh" },
  { Name: "Ji Dzmura", Edit: "Jiří Džmura", Sport: "Bobsleigh" },
  { Name: "Ji Dzmura", Edit: "Jiří Džmura", Sport: "Bobsleigh" },
  { Name: "Patrik Eli", Edit: "Patrik Eliáš", Sport: "Ice Hockey" },
  { Name: "Patrik Eli", Edit: "Patrik Eliáš", Sport: "Ice Hockey" },
  { Name: "Patrik Eli", Edit: "Patrik Eliáš", Sport: "Ice Hockey" },
  { Name: "Patrik Eli", Edit: "Patrik Eliáš", Sport: "Ice Hockey" },
  { Name: "Petra Elsterov", Edit: "Petra Elsterová", Sport: "Snowboarding" },
  { Name: "Martin Erat", Edit: "Martin Erat", Sport: "Ice Hockey" },
  { Name: "Martin Erat", Edit: "Martin Erat", Sport: "Ice Hockey" },
  { Name: "Martin Erat", Edit: "Martin Erat", Sport: "Ice Hockey" },
  {
    Name: "Karolna Erbanov",
    Edit: "Karolína Erbanová",
    Sport: "Speed Skating",
  },
  {
    Name: "Karolna Erbanov",
    Edit: "Karolína Erbanová",
    Sport: "Speed Skating",
  },
  {
    Name: "Karolna Erbanov",
    Edit: "Karolína Erbanová",
    Sport: "Speed Skating",
  },
  {
    Name: "Karolna Erbanov",
    Edit: "Karolína Erbanová",
    Sport: "Speed Skating",
  },
  {
    Name: "Karolna Erbanov",
    Edit: "Karolína Erbanová",
    Sport: "Speed Skating",
  },
  {
    Name: "Karolna Erbanov",
    Edit: "Karolína Erbanová",
    Sport: "Speed Skating",
  },
  { Name: "Lenka Faltusov", Edit: "Lenka Faltusová", Sport: "Biathlon" },
  { Name: "Lenka Faltusov", Edit: "Lenka Faltusová", Sport: "Biathlon" },
  { Name: "Lenka Faltusov", Edit: "Lenka Faltusová", Sport: "Biathlon" },
  { Name: "Marek Fiurek", Edit: "Marek Fiurášek", Sport: "Nordic Combined" },
  { Name: "Tom Fleischmann", Edit: "Tomáš Fleischmann", Sport: "Ice Hockey" },
  { Name: "Michael Frolk", Edit: "Michael Frolík", Sport: "Ice Hockey" },
  { Name: "Petr Garabk", Edit: "Petr Garabík", Sport: "Biathlon" },
  { Name: "Petr Garabk", Edit: "Petr Garabík", Sport: "Biathlon" },
  { Name: "Petr Garabk", Edit: "Petr Garabík", Sport: "Biathlon" },
  { Name: "Petr Garabk", Edit: "Petr Garabík", Sport: "Biathlon" },
  { Name: "Petr Garabk", Edit: "Petr Garabík", Sport: "Biathlon" },
  { Name: "Petr Garabk", Edit: "Petr Garabík", Sport: "Biathlon" },
  { Name: "Petr Garabk", Edit: "Petr Garabík", Sport: "Biathlon" },
  { Name: "Petr Garabk", Edit: "Petr Garabík", Sport: "Biathlon" },
  { Name: "Petr Garabk", Edit: "Petr Garabík", Sport: "Biathlon" },
  { Name: "Pavel Geffert", Edit: "Pavel Geffert", Sport: "Ice Hockey" },
  { Name: "Roman Gomola", Edit: "Roman Gomola", Sport: "Bobsleigh" },
  { Name: "Roman Gomola", Edit: "Roman Gomola", Sport: "Bobsleigh" },
  { Name: "Roman Gomola", Edit: "Roman Gomola", Sport: "Bobsleigh" },
  {
    Name: "Karolna Grohov",
    Edit: "Karolína Grohová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Karolna Grohov",
    Edit: "Karolína Grohová",
    Sport: "Cross Country Skiing",
  },
  { Name: "Radko Gudas", Edit: "Radko Gudas", Sport: "Ice Hockey" },
  { Name: "Antonn Hjek", Edit: "Antonín Hájek", Sport: "Ski Jumping" },
  { Name: "Antonn Hjek", Edit: "Antonín Hájek", Sport: "Ski Jumping" },
  { Name: "Antonn Hjek", Edit: "Antonín Hájek", Sport: "Ski Jumping" },
  { Name: "Antonn Hjek", Edit: "Antonín Hájek", Sport: "Ski Jumping" },
  { Name: "Antonn Hjek", Edit: "Antonín Hájek", Sport: "Ski Jumping" },
  { Name: "Kamila Hjkov", Edit: "Kamila Hájková", Sport: "Figure Skating" },
  {
    Name: "Eva Hkov (Bureov-)",
    Edit: "Eva Háková (Burešová)",
    Sport: "Biathlon",
  },
  {
    Name: "Eva Hkov (Bureov-)",
    Edit: "Eva Háková (Burešová)",
    Sport: "Biathlon",
  },
  {
    Name: "Eva Hkov (Bureov-)",
    Edit: "Eva Háková (Burešová)",
    Sport: "Biathlon",
  },
  {
    Name: "Eva Hkov (Bureov-)",
    Edit: "Eva Háková (Burešová)",
    Sport: "Biathlon",
  },
  {
    Name: "Eva Hkov (Bureov-)",
    Edit: "Eva Háková (Burešová)",
    Sport: "Biathlon",
  },
  {
    Name: "Eva Hkov (Bureov-)",
    Edit: "Eva Háková (Burešová)",
    Sport: "Biathlon",
  },
  {
    Name: "Eva Hkov (Bureov-)",
    Edit: "Eva Háková (Burešová)",
    Sport: "Biathlon",
  },
  {
    Name: "Eva Hkov (Bureov-)",
    Edit: "Eva Háková (Burešová)",
    Sport: "Biathlon",
  },
  {
    Name: "Eva Hkov (Bureov-)",
    Edit: "Eva Háková (Burešová)",
    Sport: "Biathlon",
  },
  {
    Name: "Eva Hkov (Bureov-)",
    Edit: "Eva Háková (Burešová)",
    Sport: "Biathlon",
  },
  { Name: "Roman Hamrlk", Edit: "Roman Hamrlík", Sport: "Ice Hockey" },
  { Name: "Roman Hamrlk", Edit: "Roman Hamrlík", Sport: "Ice Hockey" },
  {
    Name: "Kateina Hanuov-Nash",
    Edit: "Kateina Nash (Hanušová)",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Hanuov-Nash",
    Edit: "Kateina Nash (Hanušová)",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Hanuov-Nash",
    Edit: "Kateina Nash (Hanušová)",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Hanuov-Nash",
    Edit: "Kateina Nash (Hanušová)",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Hanuov-Nash",
    Edit: "Kateina Nash (Hanušová)",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Hanuov-Nash",
    Edit: "Kateina Nash (Hanušová)",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Hanuov-Nash",
    Edit: "Kateina Nash (Hanušová)",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Hanuov-Nash",
    Edit: "Kateina Nash (Hanušová)",
    Sport: "Cross Country Skiing",
  },
  { Name: "Martin Hanzal", Edit: "Martin Hanzal", Sport: "Ice Hockey" },
  { Name: "Dominik Haek", Edit: "Dominik Hašek", Sport: "Ice Hockey" },
  { Name: "Dominik Haek", Edit: "Dominik Hašek", Sport: "Ice Hockey" },
  { Name: "Dominik Haek", Edit: "Dominik Hašek", Sport: "Ice Hockey" },
  { Name: "Martin Havlt", Edit: "Martin Havlát", Sport: "Ice Hockey" },
  { Name: "Martin Havlt", Edit: "Martin Havlát", Sport: "Ice Hockey" },
  { Name: "Stanley Hayer", Edit: "Stanley Hayer", Sport: "Alpine Skiing" },
  { Name: "Stanley Hayer", Edit: "Stanley Hayer", Sport: "Alpine Skiing" },
  { Name: "Stanley Hayer", Edit: "Stanley Hayer", Sport: "Alpine Skiing" },
  { Name: "Jan Hejda", Edit: "Jan Hejda", Sport: "Ice Hockey" },
  { Name: "Milan Hejduk", Edit: "Milan Hejduk", Sport: "Ice Hockey" },
  { Name: "Milan Hejduk", Edit: "Milan Hejduk", Sport: "Ice Hockey" },
  { Name: "Milan Hejduk", Edit: "Milan Hejduk", Sport: "Ice Hockey" },
  { Name: "Ale Hemsk", Edit: "Aleš Hemský", Sport: "Ice Hockey" },
  { Name: "Ale Hemsk", Edit: "Aleš Hemský", Sport: "Ice Hockey" },
  { Name: "Luk Hemansk", Edit: "Lukáš Heřmanský", Sport: "Nordic Combined" },
  { Name: "Luk Hlava", Edit: "Lukáš Hlava", Sport: "Ski Jumping" },
  { Name: "Luk Hlava", Edit: "Lukáš Hlava", Sport: "Ski Jumping" },
  { Name: "Luk Hlava", Edit: "Lukáš Hlava", Sport: "Ski Jumping" },
  { Name: "Milan Hnilika", Edit: "Milan Hnilička", Sport: "Ice Hockey" },
  { Name: "Jan Holick", Edit: "Jan Holický", Sport: "Alpine Skiing" },
  { Name: "Jan Holick", Edit: "Jan Holický", Sport: "Alpine Skiing" },
  { Name: "Jan Holick", Edit: "Jan Holický", Sport: "Alpine Skiing" },
  { Name: "Ji Holubec", Edit: "Jiří Holubec", Sport: "Biathlon" },
  { Name: "Ji Holubec", Edit: "Jiří Holubec", Sport: "Biathlon" },
  { Name: "Ji Holubec", Edit: "Jiří Holubec", Sport: "Biathlon" },
  { Name: "Ji Holubec", Edit: "Jiří Holubec", Sport: "Biathlon" },
  { Name: "Ji Holubec", Edit: "Jiří Holubec", Sport: "Biathlon" },
  { Name: "Tom Holubec", Edit: "Tomáš Holubec", Sport: "Biathlon" },
  { Name: "Tom Holubec", Edit: "Tomáš Holubec", Sport: "Biathlon" },
  { Name: "Tom Holubec", Edit: "Tomáš Holubec", Sport: "Biathlon" },
  { Name: "Roman Hork", Edit: "Roman Horák", Sport: "Ice Hockey" },
  { Name: "Miloslav Hoava", Edit: "Miloslav Hořava", Sport: "Ice Hockey" },
  { Name: "Martin Hostk", Edit: "Martin Hosták", Sport: "Ice Hockey" },
  { Name: "Petr Hrbek", Edit: "Petr Hrbek", Sport: "Ice Hockey" },
  { Name: "Jan Hrdina", Edit: "Jan Hrdina", Sport: "Ice Hockey" },
  { Name: "Lucie Hrstkov", Edit: "Lucie Hrstková", Sport: "Alpine Skiing" },
  { Name: "Lucie Hrstkov", Edit: "Lucie Hrstková", Sport: "Alpine Skiing" },
  { Name: "Lucie Hrstkov", Edit: "Lucie Hrstková", Sport: "Alpine Skiing" },
  { Name: "Lucie Hrstkov", Edit: "Lucie Hrstková", Sport: "Alpine Skiing" },
  { Name: "Lucie Hrstkov", Edit: "Lucie Hrstková", Sport: "Alpine Skiing" },
  { Name: "Lucie Hrstkov", Edit: "Lucie Hrstková", Sport: "Alpine Skiing" },
  { Name: "Lucie Hrstkov", Edit: "Lucie Hrstková", Sport: "Alpine Skiing" },
  { Name: "Lucie Hrstkov", Edit: "Lucie Hrstková", Sport: "Alpine Skiing" },
  { Name: "Lucie Hrstkov", Edit: "Lucie Hrstková", Sport: "Alpine Skiing" },
  { Name: "Lucie Hrstkov", Edit: "Lucie Hrstková", Sport: "Alpine Skiing" },
  { Name: "Lucie Hrstkov", Edit: "Lucie Hrstková", Sport: "Alpine Skiing" },
  { Name: "Lucie Hrstkov", Edit: "Lucie Hrstková", Sport: "Alpine Skiing" },
  { Name: "Lucie Hrstkov", Edit: "Lucie Hrstková", Sport: "Alpine Skiing" },
  { Name: "Jakub Hyman", Edit: "Jakub Hyman", Sport: "Luge" },
  { Name: "Jakub Hyman", Edit: "Jakub Hyman", Sport: "Luge" },
  { Name: "Ondej Hyman", Edit: "Ondej Hyman", Sport: "Luge" },
  { Name: "Ondej Hyman", Edit: "Ondej Hyman", Sport: "Luge" },
  { Name: "Ondej Hyman", Edit: "Ondej Hyman", Sport: "Luge" },
  { Name: "Jaromr Jgr", Edit: "Jaromír Jágr", Sport: "Ice Hockey" },
  { Name: "Jaromr Jgr", Edit: "Jaromír Jágr", Sport: "Ice Hockey" },
  { Name: "Jaromr Jgr", Edit: "Jaromír Jágr", Sport: "Ice Hockey" },
  { Name: "Jaromr Jgr", Edit: "Jaromír Jágr", Sport: "Ice Hockey" },
  { Name: "Jaromr Jgr", Edit: "Jaromír Jágr", Sport: "Ice Hockey" },
  { Name: "Martin Jak", Edit: "Martin Jakš", Sport: "Cross Country Skiing" },
  { Name: "Martin Jak", Edit: "Martin Jakš", Sport: "Cross Country Skiing" },
  { Name: "Martin Jak", Edit: "Martin Jakš", Sport: "Cross Country Skiing" },
  { Name: "Martin Jak", Edit: "Martin Jakš", Sport: "Cross Country Skiing" },
  { Name: "Martin Jak", Edit: "Martin Jakš", Sport: "Cross Country Skiing" },
  { Name: "Martin Jak", Edit: "Martin Jakš", Sport: "Cross Country Skiing" },
  { Name: "Martin Jak", Edit: "Martin Jakš", Sport: "Cross Country Skiing" },
  { Name: "Jakub Janda", Edit: "Jakub Janda", Sport: "Ski Jumping" },
  { Name: "Jakub Janda", Edit: "Jakub Janda", Sport: "Ski Jumping" },
  { Name: "Jakub Janda", Edit: "Jakub Janda", Sport: "Ski Jumping" },
  { Name: "Jakub Janda", Edit: "Jakub Janda", Sport: "Ski Jumping" },
  { Name: "Jakub Janda", Edit: "Jakub Janda", Sport: "Ski Jumping" },
  { Name: "Jakub Janda", Edit: "Jakub Janda", Sport: "Ski Jumping" },
  { Name: "Jakub Janda", Edit: "Jakub Janda", Sport: "Ski Jumping" },
  { Name: "Jakub Janda", Edit: "Jakub Janda", Sport: "Ski Jumping" },
  { Name: "Jakub Janda", Edit: "Jakub Janda", Sport: "Ski Jumping" },
  { Name: "Jakub Janda", Edit: "Jakub Janda", Sport: "Ski Jumping" },
  { Name: "Jakub Janda", Edit: "Jakub Janda", Sport: "Ski Jumping" },
  { Name: "Jakub Janda", Edit: "Jakub Janda", Sport: "Ski Jumping" },
  { Name: "Ivana ", Edit: "Ivana Janečková", Sport: "Cross Country Skiing" },
  { Name: "Ivana ", Edit: "Ivana Janečková", Sport: "Cross Country Skiing" },
  { Name: "Ivana ", Edit: "Ivana Janečková", Sport: "Cross Country Skiing" },
  { Name: "Ivana ", Edit: "Ivana Janečková", Sport: "Cross Country Skiing" },
  { Name: "Ivana ", Edit: "Ivana Janečková", Sport: "Cross Country Skiing" },
  { Name: "Ivana ", Edit: "Ivana Janečková", Sport: "Cross Country Skiing" },
  { Name: "Otakar Janeck", Edit: "Otakar Janecký", Sport: "Ice Hockey" },
  { Name: "Markta Jeriov", Edit: "Markéta Jeriová", Sport: "Luge" },
  { Name: "Markta Jeriov", Edit: "Markéta Jeriová", Sport: "Luge" },
  { Name: "Frantiek Je", Edit: "Frantiek Jež", Sport: "Ski Jumping" },
  { Name: "Frantiek Je", Edit: "Frantiek Jež", Sport: "Ski Jumping" },
  { Name: "Frantiek Je", Edit: "Frantiek Jež", Sport: "Ski Jumping" },
  { Name: "Lubo Jra", Edit: "Luboš Jíra", Sport: "Luge" },
  { Name: "Frantiek Kaberle", Edit: "František Kaberle", Sport: "Ice Hockey" },
  { Name: "Tom Kaberle", Edit: "Tomáš Kaberle", Sport: "Ice Hockey" },
  { Name: "Tom Kaberle", Edit: "Tomáš Kaberle", Sport: "Ice Hockey" },
  { Name: "Tom Kaberle", Edit: "Tomáš Kaberle", Sport: "Ice Hockey" },
  { Name: "Tom Kaberle", Edit: "Tomáš Kaberle", Sport: "Ice Hockey" },
  { Name: "Drahomr Kadlec", Edit: "Drahomír Kadlec", Sport: "Ice Hockey" },
  { Name: "Tom Kapusta", Edit: "Tomáš Kapusta", Sport: "Ice Hockey" },
  { Name: "Kamil Kak", Edit: "Kamil Kašťák", Sport: "Ice Hockey" },
  { Name: "Iveta Knkov", Edit: "Iveta Knížková", Sport: "Biathlon" },
  { Name: "Iveta Knkov", Edit: "Iveta Knížková", Sport: "Biathlon" },
  { Name: "Iveta Knkov", Edit: "Iveta Knížková", Sport: "Biathlon" },
  { Name: "Jan Kobin", Edit: "Jan Kobián", Sport: "Bobsleigh" },
  { Name: "Jan Kobin", Edit: "Jan Kobián", Sport: "Bobsleigh" },
  { Name: "Jan Kobin", Edit: "Jan Kobián", Sport: "Bobsleigh" },
  { Name: "Jan Kobin", Edit: "Jan Kobián", Sport: "Bobsleigh" },
  { Name: "Jan Kobin", Edit: "Jan Kobián", Sport: "Bobsleigh" },
  { Name: "Jan Kobin", Edit: "Jan Kobián", Sport: "Bobsleigh" },
  { Name: "Jan Kobin", Edit: "Jan Kobián", Sport: "Bobsleigh" },
  { Name: "Jan Kobin", Edit: "Jan Kobián", Sport: "Bobsleigh" },
  { Name: "Jan Kobin", Edit: "Jan Kobián", Sport: "Bobsleigh" },
  {
    Name: "Zuzana Kocumov",
    Edit: "Zuzana Kocumová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Zuzana Kocumov",
    Edit: "Zuzana Kocumová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Zuzana Kocumov",
    Edit: "Zuzana Kocumová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Zuzana Kocumov",
    Edit: "Zuzana Kocumová",
    Sport: "Cross Country Skiing",
  },
  { Name: "Peter Kondrt", Edit: "Peter Kondrát", Sport: "Bobsleigh" },
  { Name: "Peter Kondrt", Edit: "Peter Kondrát", Sport: "Bobsleigh" },
  {
    Name: "Martina Konopov",
    Edit: "Martina Konopová",
    Sport: "Freestyle Skiing",
  },
  { Name: "Miroslav Kopal", Edit: "Miroslav Kopal", Sport: "Nordic Combined" },
  {
    Name: "Vclav Korunka",
    Edit: "Václav Korunka",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Vclav Korunka",
    Edit: "Václav Korunka",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Vclav Korunka",
    Edit: "Václav Korunka",
    Sport: "Cross Country Skiing",
  },
  { Name: "Tom Kos", Edit: "Tomáš Kos", Sport: "Biathlon" },
  { Name: "Tom Kos", Edit: "Tomáš Kos", Sport: "Biathlon" },
  { Name: "Ale Kotalk", Edit: "Aleš Kotalík", Sport: "Ice Hockey" },
  { Name: "Vendula Kotenov", Edit: "Vendula Kotenová", Sport: "Luge" },
  { Name: "Vendula Kotenov", Edit: "Vendula Kotenová", Sport: "Luge" },
  { Name: "Roman Koudelka", Edit: "Roman Koudelka", Sport: "Ski Jumping" },
  { Name: "Roman Koudelka", Edit: "Roman Koudelka", Sport: "Ski Jumping" },
  { Name: "Roman Koudelka", Edit: "Roman Koudelka", Sport: "Ski Jumping" },
  { Name: "Roman Koudelka", Edit: "Roman Koudelka", Sport: "Ski Jumping" },
  { Name: "Roman Koudelka", Edit: "Roman Koudelka", Sport: "Ski Jumping" },
  { Name: "Roman Koudelka", Edit: "Roman Koudelka", Sport: "Ski Jumping" },
  {
    Name: "Martin Koukal",
    Edit: "Martin Koukal",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martin Koukal",
    Edit: "Martin Koukal",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martin Koukal",
    Edit: "Martin Koukal",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martin Koukal",
    Edit: "Martin Koukal",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martin Koukal",
    Edit: "Martin Koukal",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martin Koukal",
    Edit: "Martin Koukal",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martin Koukal",
    Edit: "Martin Koukal",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martin Koukal",
    Edit: "Martin Koukal",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martin Koukal",
    Edit: "Martin Koukal",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martin Koukal",
    Edit: "Martin Koukal",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martin Koukal",
    Edit: "Martin Koukal",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martin Koukal",
    Edit: "Martin Koukal",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martin Koukal",
    Edit: "Martin Koukal",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martin Koukal",
    Edit: "Martin Koukal",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martin Koukal",
    Edit: "Martin Koukal",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martin Koukal",
    Edit: "Martin Koukal",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Kovalov",
    Edit: "Kateřina Kovalová",
    Sport: "Figure Skating",
  },
  { Name: "Jakub Kov", Edit: "Jakub Kovář", Sport: "Ice Hockey" },
  { Name: "Radka Kovakov", Edit: "Radka Kovaříková", Sport: "Figure Skating" },
  { Name: "Duan Koek", Edit: "Dušan Kožíšek", Sport: "Cross Country Skiing" },
  { Name: "Duan Koek", Edit: "Dušan Kožíšek", Sport: "Cross Country Skiing" },
  { Name: "Duan Koek", Edit: "Dušan Kožíšek", Sport: "Cross Country Skiing" },
  { Name: "Duan Koek", Edit: "Dušan Kožíšek", Sport: "Cross Country Skiing" },
  { Name: "Duan Koek", Edit: "Dušan Kožíšek", Sport: "Cross Country Skiing" },
  { Name: "Duan Koek", Edit: "Dušan Kožíšek", Sport: "Cross Country Skiing" },
  { Name: "Duan Koek", Edit: "Dušan Kožíšek", Sport: "Cross Country Skiing" },
  { Name: "Ondej Kozlovsk", Edit: "Ondřej Kozlovský", Sport: "Bobsleigh" },
  { Name: "Luk Krajek", Edit: "Lukáš Krajíček", Sport: "Ice Hockey" },
  { Name: "David Kramr", Edit: "David Kramár", Sport: "Speed Skating" },
  { Name: "Tom Kraus", Edit: "Tomáš Kraus", Sport: "Freestyle Skiing" },
  { Name: "Tom Kraus", Edit: "Tomáš Kraus", Sport: "Freestyle Skiing" },
  { Name: "Michal Krm", Edit: "Michal Krčmář", Sport: "Biathlon" },
  { Name: "Michal Krm", Edit: "Michal Krčmář", Sport: "Biathlon" },
  { Name: "David Kreji", Edit: "David Krejčí", Sport: "Ice Hockey" },
  { Name: "David Kreji", Edit: "David Krejčí", Sport: "Ice Hockey" },
  { Name: "Klra Kov", Edit: "Klára Křížová", Sport: "Alpine Skiing" },
  { Name: "Klra Kov", Edit: "Klára Křížová", Sport: "Alpine Skiing" },
  { Name: "Klra Kov", Edit: "Klára Křížová", Sport: "Alpine Skiing" },
  { Name: "Klra Kov", Edit: "Klára Křížová", Sport: "Alpine Skiing" },
  { Name: "Klra Kov", Edit: "Klára Křížová", Sport: "Alpine Skiing" },
  { Name: "Zbynk Krompolc", Edit: "Zbyněk Krompolc", Sport: "Ski Jumping" },
  { Name: "Zbynk Krompolc", Edit: "Zbyněk Krompolc", Sport: "Ski Jumping" },
  { Name: "Zbynk Krompolc", Edit: "Zbyněk Krompolc", Sport: "Ski Jumping" },
  { Name: "Tom Krupk", Edit: "Tomáš Krupčík", Sport: "Biathlon" },
  { Name: "Tom Krupk", Edit: "Tomáš Krupčík", Sport: "Biathlon" },
  { Name: "Krytof Krzl", Edit: "Kryštof Krýzl", Sport: "Alpine Skiing" },
  { Name: "Krytof Krzl", Edit: "Kryštof Krýzl", Sport: "Alpine Skiing" },
  { Name: "Krytof Krzl", Edit: "Kryštof Krýzl", Sport: "Alpine Skiing" },
  { Name: "Krytof Krzl", Edit: "Kryštof Krýzl", Sport: "Alpine Skiing" },
  { Name: "Krytof Krzl", Edit: "Kryštof Krýzl", Sport: "Alpine Skiing" },
  { Name: "Krytof Krzl", Edit: "Kryštof Krýzl", Sport: "Alpine Skiing" },
  { Name: "Krytof Krzl", Edit: "Kryštof Krýzl", Sport: "Alpine Skiing" },
  { Name: "Krytof Krzl", Edit: "Kryštof Krýzl", Sport: "Alpine Skiing" },
  { Name: "Krytof Krzl", Edit: "Kryštof Krýzl", Sport: "Alpine Skiing" },
  { Name: "Krytof Krzl", Edit: "Kryštof Krýzl", Sport: "Alpine Skiing" },
  { Name: "Krytof Krzl", Edit: "Kryštof Krýzl", Sport: "Alpine Skiing" },
  { Name: "Filip Kuba", Edit: "Filip Kuba", Sport: "Ice Hockey" },
  { Name: "Filip Kuba", Edit: "Filip Kuba", Sport: "Ice Hockey" },
  { Name: "Pavel Kubina", Edit: "Pavel Kubina", Sport: "Ice Hockey" },
  { Name: "Pavel Kubina", Edit: "Pavel Kubina", Sport: "Ice Hockey" },
  { Name: "Pavel Kubina", Edit: "Pavel Kubina", Sport: "Ice Hockey" },
  { Name: "Frantiek Kuera", Edit: "František Kučera", Sport: "Ice Hockey" },
  { Name: "Ji Kuera", Edit: "Jiří Kučera", Sport: "Ice Hockey" },
  { Name: "Milan Kuera", Edit: "Milan Kučera", Sport: "Nordic Combined" },
  { Name: "Milan Kuera", Edit: "Milan Kučera", Sport: "Nordic Combined" },
  { Name: "Milan Kuera", Edit: "Milan Kučera", Sport: "Nordic Combined" },
  { Name: "Milan Kuera", Edit: "Milan Kučera", Sport: "Nordic Combined" },
  { Name: "Milan Kuera", Edit: "Milan Kučera", Sport: "Nordic Combined" },
  { Name: "Milan Kuera", Edit: "Milan Kučera", Sport: "Nordic Combined" },
  { Name: "Milan Kuera", Edit: "Milan Kučera", Sport: "Nordic Combined" },
  { Name: "Nikol Kuerov", Edit: "Nikol Kučerová", Sport: "Freestyle Skiing" },
  {
    Name: "Jana Kulhav (-Vapenikov)",
    Edit: "Jana Kulhavá (Vápeníková)",
    Sport: "Biathlon",
  },
  { Name: "Lenka Kulovan", Edit: "Lenka Kulovaná", Sport: "Figure Skating" },
  { Name: "Lenka Kulovan", Edit: "Lenka Kulovaná", Sport: "Figure Skating" },
  { Name: "Eva Kurfrstov", Edit: "Eva Kurfirstová", Sport: "Alpine Skiing" },
  { Name: "Eva Kurfrstov", Edit: "Eva Kurfirstová", Sport: "Alpine Skiing" },
  { Name: "Eva Kurfrstov", Edit: "Eva Kurfirstová", Sport: "Alpine Skiing" },
  { Name: "Matj Kvala", Edit: "Matěj Kvíčala", Sport: "Luge" },
  { Name: "Michal Kvala", Edit: "Michal Kvíčala", Sport: "Luge" },
  { Name: "Jitka Landov", Edit: "Jitka Landová", Sport: "Biathlon" },
  { Name: "Jitka Landov", Edit: "Jitka Landová", Sport: "Biathlon" },
  { Name: "Jitka Landov", Edit: "Jitka Landová", Sport: "Biathlon" },
  { Name: "Jitka Landov", Edit: "Jitka Landová", Sport: "Biathlon" },
  { Name: "Robert Lang", Edit: "Robert Lang", Sport: "Ice Hockey" },
  { Name: "Robert Lang", Edit: "Robert Lang", Sport: "Ice Hockey" },
  { Name: "Robert Lang", Edit: "Robert Lang", Sport: "Ice Hockey" },
  { Name: "Ester Ledeck", Edit: "Ester Ledecká", Sport: "Snowboarding" },
  { Name: "Ester Ledeck", Edit: "Ester Ledecká", Sport: "Snowboarding" },
  {
    Name: "Kateina Losmanov-Holubcov",
    Edit: "Kateřina Holubcová (Losmanová)",
    Sport: "Biathlon",
  },
  {
    Name: "Kateina Losmanov-Holubcov",
    Edit: "Kateřina Holubcová (Losmanová)",
    Sport: "Biathlon",
  },
  {
    Name: "Kateina Losmanov-Holubcov",
    Edit: "Kateřina Holubcová (Losmanová)",
    Sport: "Biathlon",
  },
  {
    Name: "Kateina Losmanov-Holubcov",
    Edit: "Kateřina Holubcová (Losmanová)",
    Sport: "Biathlon",
  },
  {
    Name: "Kateina Losmanov-Holubcov",
    Edit: "Kateřina Holubcová (Losmanová)",
    Sport: "Biathlon",
  },
  {
    Name: "Kateina Losmanov-Holubcov",
    Edit: "Kateřina Holubcová (Losmanová)",
    Sport: "Biathlon",
  },
  {
    Name: "Kateina Losmanov-Holubcov",
    Edit: "Kateřina Holubcová (Losmanová)",
    Sport: "Biathlon",
  },
  {
    Name: "Kateina Losmanov-Holubcov",
    Edit: "Kateřina Holubcová (Losmanová)",
    Sport: "Biathlon",
  },
  {
    Name: "Kateina Losmanov-Holubcov",
    Edit: "Kateřina Holubcová (Losmanová)",
    Sport: "Biathlon",
  },
  {
    Name: "Kateina Losmanov-Holubcov",
    Edit: "Kateřina Holubcová (Losmanová)",
    Sport: "Biathlon",
  },
  {
    Name: "Kateina Losmanov-Holubcov",
    Edit: "Kateřina Holubcová (Losmanová)",
    Sport: "Biathlon",
  },
  {
    Name: "Vojtch Loudin",
    Edit: "Vojtěch Loudín",
    Sport: "Short Track Speed Skating",
  },
  { Name: "Ji Magl", Edit: "Jiří Magál", Sport: "Cross Country Skiing" },
  { Name: "Ji Magl", Edit: "Jiří Magál", Sport: "Cross Country Skiing" },
  { Name: "Ji Magl", Edit: "Jiří Magál", Sport: "Cross Country Skiing" },
  { Name: "Ji Magl", Edit: "Jiří Magál", Sport: "Cross Country Skiing" },
  { Name: "Ji Magl", Edit: "Jiří Magál", Sport: "Cross Country Skiing" },
  { Name: "Ji Magl", Edit: "Jiří Magál", Sport: "Cross Country Skiing" },
  { Name: "Ji Magl", Edit: "Jiří Magál", Sport: "Cross Country Skiing" },
  { Name: "Ji Magl", Edit: "Jiří Magál", Sport: "Cross Country Skiing" },
  { Name: "Ji Magl", Edit: "Jiří Magál", Sport: "Cross Country Skiing" },
  { Name: "Ji Magl", Edit: "Jiří Magál", Sport: "Cross Country Skiing" },
  { Name: "Ji Magl", Edit: "Jiří Magál", Sport: "Cross Country Skiing" },
  { Name: "Ji Magl", Edit: "Jiří Magál", Sport: "Cross Country Skiing" },
  { Name: "Ji Magl", Edit: "Jiří Magál", Sport: "Cross Country Skiing" },
  { Name: "Ji Magl", Edit: "Jiří Magál", Sport: "Cross Country Skiing" },
  { Name: "Ji Magl", Edit: "Jiří Magál", Sport: "Cross Country Skiing" },
  { Name: "Frantiek Mka", Edit: "František Máka", Sport: "Nordic Combined" },
  { Name: "Frantiek Mka", Edit: "František Máka", Sport: "Nordic Combined" },
  { Name: "Marek Malk", Edit: "Marek Malík", Sport: "Ice Hockey" },
  {
    Name: "Gabriela Martinovov",
    Edit: "Gabriela Martinovová",
    Sport: "Alpine Skiing",
  },
  {
    Name: "Gabriela Martinovov",
    Edit: "Gabriela Martinovová",
    Sport: "Alpine Skiing",
  },
  {
    Name: "Gabriela Martinovov",
    Edit: "Gabriela Martinovová",
    Sport: "Alpine Skiing",
  },
  { Name: "Ivan Masak", Edit: "Ivan Masařík", Sport: "Biathlon" },
  { Name: "Ivan Masak", Edit: "Ivan Masařík", Sport: "Biathlon" },
  { Name: "Ivan Masak", Edit: "Ivan Masařík", Sport: "Biathlon" },
  { Name: "Ivan Masak", Edit: "Ivan Masařík", Sport: "Biathlon" },
  { Name: "Ivan Masak", Edit: "Ivan Masařík", Sport: "Biathlon" },
  { Name: "Ivan Masak", Edit: "Ivan Masařík", Sport: "Biathlon" },
  { Name: "Ivan Masak", Edit: "Ivan Masařík", Sport: "Biathlon" },
  { Name: "Jan Matura", Edit: "Jan Matura", Sport: "Nordic Combined" },
  { Name: "Jan Matura", Edit: "Jan Matura", Sport: "Nordic Combined" },
  { Name: "Jan Matura", Edit: "Jan Matura", Sport: "Ski Jumping" },
  { Name: "Jan Matura", Edit: "Jan Matura", Sport: "Ski Jumping" },
  { Name: "Jan Matura", Edit: "Jan Matura", Sport: "Ski Jumping" },
  { Name: "Jan Matura", Edit: "Jan Matura", Sport: "Ski Jumping" },
  { Name: "Jan Matura", Edit: "Jan Matura", Sport: "Ski Jumping" },
  { Name: "Jan Matura", Edit: "Jan Matura", Sport: "Ski Jumping" },
  { Name: "Jan Matura", Edit: "Jan Matura", Sport: "Ski Jumping" },
  { Name: "Jan Matura", Edit: "Jan Matura", Sport: "Ski Jumping" },
  { Name: "Jan Matura", Edit: "Jan Matura", Sport: "Ski Jumping" },
  { Name: "Marcel Maxa", Edit: "Marcel Maxa", Sport: "Alpine Skiing" },
  { Name: "Marcel Maxa", Edit: "Marcel Maxa", Sport: "Alpine Skiing" },
  { Name: "Marcel Maxa", Edit: "Marcel Maxa", Sport: "Alpine Skiing" },
  { Name: "Jan Mazoch", Edit: "Jan Mazoch", Sport: "Ski Jumping" },
  { Name: "Jan Mazoch", Edit: "Jan Mazoch", Sport: "Ski Jumping" },
  { Name: "Jan Mazoch", Edit: "Jan Mazoch", Sport: "Ski Jumping" },
  { Name: "Jan Mazoch", Edit: "Jan Mazoch", Sport: "Ski Jumping" },
  { Name: "Milan Michlek", Edit: "Milan Michálek", Sport: "Ice Hockey" },
  { Name: "Milan Michlek", Edit: "Milan Michálek", Sport: "Ice Hockey" },
  { Name: "Zbynk Michlek", Edit: "Zbyněk Michálek", Sport: "Ice Hockey" },
  { Name: "Zbynk Michlek", Edit: "Zbyněk Michálek", Sport: "Ice Hockey" },
  { Name: "Petr Michl", Edit: "Petr Michl", Sport: "Cross Country Skiing" },
  { Name: "Petr Michl", Edit: "Petr Michl", Sport: "Cross Country Skiing" },
  { Name: "Petr Michl", Edit: "Petr Michl", Sport: "Cross Country Skiing" },
  { Name: "Petr Michl", Edit: "Petr Michl", Sport: "Cross Country Skiing" },
  { Name: "Petr Michl", Edit: "Petr Michl", Sport: "Cross Country Skiing" },
  { Name: "Petr Michl", Edit: "Petr Michl", Sport: "Cross Country Skiing" },
  { Name: "Petr Michl", Edit: "Petr Michl", Sport: "Cross Country Skiing" },
  { Name: "Petr Michl", Edit: "Petr Michl", Sport: "Cross Country Skiing" },
  { Name: "Petr Michl", Edit: "Petr Michl", Sport: "Cross Country Skiing" },
  {
    Name: "Klra Moravcov",
    Edit: "Klára Moravcová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Klra Moravcov",
    Edit: "Klára Moravcová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Klra Moravcov",
    Edit: "Klára Moravcová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Klra Moravcov",
    Edit: "Klára Moravcová",
    Sport: "Cross Country Skiing",
  },
  { Name: "David Moravec", Edit: "David Moravec", Sport: "Ice Hockey" },
  { Name: "Ondej Moravec", Edit: "Ondřej Moravec", Sport: "Biathlon" },
  { Name: "Ondej Moravec", Edit: "Ondřej Moravec", Sport: "Biathlon" },
  { Name: "Ondej Moravec", Edit: "Ondřej Moravec", Sport: "Biathlon" },
  { Name: "Ondej Moravec", Edit: "Ondřej Moravec", Sport: "Biathlon" },
  { Name: "Ondej Moravec", Edit: "Ondřej Moravec", Sport: "Biathlon" },
  { Name: "Ondej Moravec", Edit: "Ondřej Moravec", Sport: "Biathlon" },
  { Name: "Ondej Moravec", Edit: "Ondřej Moravec", Sport: "Biathlon" },
  { Name: "Ondej Moravec", Edit: "Ondřej Moravec", Sport: "Biathlon" },
  { Name: "Ondej Moravec", Edit: "Ondřej Moravec", Sport: "Biathlon" },
  { Name: "Ondej Moravec", Edit: "Ondřej Moravec", Sport: "Biathlon" },
  { Name: "Kateina Mrzov", Edit: "Kateřina Mrázová", Sport: "Figure Skating" },
  { Name: "Kateina Mrzov", Edit: "Kateřina Mrázová", Sport: "Figure Skating" },
  { Name: "Petr Nedvd", Edit: "Petr Nedvěd", Sport: "Ice Hockey" },
  {
    Name: "Kateina Neumannov",
    Edit: "Kateřina Neumannová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Neumannov",
    Edit: "Kateřina Neumannová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Neumannov",
    Edit: "Kateřina Neumannová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Neumannov",
    Edit: "Kateřina Neumannová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Neumannov",
    Edit: "Kateřina Neumannová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Neumannov",
    Edit: "Kateřina Neumannová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Neumannov",
    Edit: "Kateřina Neumannová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Neumannov",
    Edit: "Kateřina Neumannová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Neumannov",
    Edit: "Kateřina Neumannová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Neumannov",
    Edit: "Kateřina Neumannová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Neumannov",
    Edit: "Kateřina Neumannová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Neumannov",
    Edit: "Kateřina Neumannová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Neumannov",
    Edit: "Kateřina Neumannová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Neumannov",
    Edit: "Kateřina Neumannová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Neumannov",
    Edit: "Kateřina Neumannová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Neumannov",
    Edit: "Kateřina Neumannová",
    Sport: "Cross Country Skiing",
  },
  { Name: "Emil Novk", Edit: "Emil Novák", Sport: "Snowboarding" },
  { Name: "Petr Novk", Edit: "Petr Novák", Sport: "Cross Country Skiing" },
  { Name: "Petr Novk", Edit: "Petr Novák", Sport: "Cross Country Skiing" },
  {
    Name: "Petra Novkov",
    Edit: "Petra Nováková",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Petra Novkov",
    Edit: "Petra Nováková",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Petra Novkov",
    Edit: "Petra Nováková",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Petra Novkov",
    Edit: "Petra Nováková",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kateina Novotn",
    Edit: "Kateřina Novotná",
    Sport: "Short Track Speed Skating",
  },
  {
    Name: "Kateina Novotn",
    Edit: "Kateřina Novotná",
    Sport: "Short Track Speed Skating",
  },
  {
    Name: "Kateina Novotn",
    Edit: "Kateřina Novotná",
    Sport: "Short Track Speed Skating",
  },
  {
    Name: "Kateina Novotn",
    Edit: "Kateřina Novotná",
    Sport: "Short Track Speed Skating",
  },
  {
    Name: "Kateina Novotn",
    Edit: "Kateřina Novotná",
    Sport: "Short Track Speed Skating",
  },
  {
    Name: "Kateina Novotn",
    Edit: "Kateřina Novotná",
    Sport: "Short Track Speed Skating",
  },
  {
    Name: "Kateina Novotn",
    Edit: "Kateřina Novotná",
    Sport: "Short Track Speed Skating",
  },
  {
    Name: "Kateina Novotn",
    Edit: "Kateřina Novotná",
    Sport: "Short Track Speed Skating",
  },
  {
    Name: "Kateina Novotn",
    Edit: "Kateřina Novotná",
    Sport: "Short Track Speed Skating",
  },
  {
    Name: "Kateina Novotn",
    Edit: "Kateřina Novotná",
    Sport: "Short Track Speed Skating",
  },
  {
    Name: "Kateina Novotn",
    Edit: "Kateřina Novotná",
    Sport: "Short Track Speed Skating",
  },
  {
    Name: "Irena Novotn-esnekov",
    Edit: "Irena Česneková (Novotná)",
    Sport: "Biathlon",
  },
  {
    Name: "Irena Novotn-esnekov",
    Edit: "Irena Česneková (Novotná)",
    Sport: "Biathlon",
  },
  {
    Name: "Irena Novotn-esnekov",
    Edit: "Irena Česneková (Novotná)",
    Sport: "Biathlon",
  },
  {
    Name: "Irena Novotn-esnekov",
    Edit: "Irena Česneková (Novotná)",
    Sport: "Biathlon",
  },
  {
    Name: "Irena Novotn-esnekov",
    Edit: "Irena Česneková (Novotná)",
    Sport: "Biathlon",
  },
  {
    Name: "Irena Novotn-esnekov",
    Edit: "Irena Česneková (Novotná)",
    Sport: "Biathlon",
  },
  {
    Name: "Irena Novotn-esnekov",
    Edit: "Irena Česneková (Novotná)",
    Sport: "Biathlon",
  },
  {
    Name: "Irena Novotn-esnekov",
    Edit: "Irena Česneková (Novotná)",
    Sport: "Biathlon",
  },
  {
    Name: "Irena Novotn-esnekov",
    Edit: "Irena Česneková (Novotná)",
    Sport: "Biathlon",
  },
  { Name: "Ji Novotn", Edit: "Jiří Novotný", Sport: "Ice Hockey" },
  { Name: "Michal Novotn", Edit: "Michal Novotný", Sport: "Snowboarding" },
  { Name: "Michal Novotn", Edit: "Michal Novotný", Sport: "Snowboarding" },
  { Name: "Ren Novotn", Edit: "René Novotný", Sport: "Figure Skating" },
  { Name: "Rostislav Olesz", Edit: "Rostislav Olesz", Sport: "Ice Hockey" },
  { Name: "Ondej Palt", Edit: "Ondřej Palát", Sport: "Ice Hockey" },
  { Name: "rka Panochov", Edit: "Šárka Pančochová", Sport: "Snowboarding" },
  { Name: "rka Panochov", Edit: "Šárka Pančochová", Sport: "Snowboarding" },
  { Name: "rka Panochov", Edit: "Šárka Pančochová", Sport: "Snowboarding" },
  { Name: "Zbynk Pnek", Edit: "Zbyněk Pánek", Sport: "Nordic Combined" },
  { Name: "Zbynk Pnek", Edit: "Zbyněk Pánek", Sport: "Nordic Combined" },
  { Name: "Ji Parma", Edit: "Jiří Parma", Sport: "Ski Jumping" },
  { Name: "Ji Parma", Edit: "Jiří Parma", Sport: "Ski Jumping" },
  { Name: "Ji Parma", Edit: "Jiří Parma", Sport: "Ski Jumping" },
  { Name: "Pavel Patera", Edit: "Pavel Patera", Sport: "Ice Hockey" },
  { Name: "Pavel Patera", Edit: "Pavel Patera", Sport: "Ice Hockey" },
  {
    Name: "Kateina Paulthov",
    Edit: "Kateřina Pauláthová",
    Sport: "Alpine Skiing",
  },
  {
    Name: "Kateina Paulthov",
    Edit: "Kateřina Pauláthová",
    Sport: "Alpine Skiing",
  },
  {
    Name: "Kateina Paulthov",
    Edit: "Kateřina Pauláthová",
    Sport: "Alpine Skiing",
  },
  { Name: "Ondej Pavelec", Edit: "Ondřej Pavelec", Sport: "Ice Hockey" },
  {
    Name: "Martin Petrsek",
    Edit: "Martin Petrásek",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martin Petrsek",
    Edit: "Martin Petrásek",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martin Petrsek",
    Edit: "Martin Petrásek",
    Sport: "Cross Country Skiing",
  },
  { Name: "Tom Plekanec", Edit: "Tomáš Plekanec", Sport: "Ice Hockey" },
  { Name: "Tom Plekanec", Edit: "Tomáš Plekanec", Sport: "Ice Hockey" },
  { Name: "Roman Polk", Edit: "Roman Polák", Sport: "Ice Hockey" },
  { Name: "Pavel Polomsk", Edit: "Pavel Polomský", Sport: "Bobsleigh" },
  { Name: "Pavel Polomsk", Edit: "Pavel Polomský", Sport: "Bobsleigh" },
  { Name: "Pavel Polomsk", Edit: "Pavel Polomský", Sport: "Bobsleigh" },
  { Name: "Pavel Polomsk", Edit: "Pavel Polomský", Sport: "Bobsleigh" },
  { Name: "Tom Portyk", Edit: "Tomáš Portyk", Sport: "Nordic Combined" },
  { Name: "Tom Portyk", Edit: "Tomáš Portyk", Sport: "Nordic Combined" },
  { Name: "Tom Portyk", Edit: "Tomáš Portyk", Sport: "Nordic Combined" },
  { Name: "Libor Prochzka", Edit: "Libor Procházka", Sport: "Ice Hockey" },
  { Name: "Martin Prochzka", Edit: "Martin Procházka", Sport: "Ice Hockey" },
  { Name: "Vclav Prospal", Edit: "Václav Prospal", Sport: "Ice Hockey" },
  { Name: "Pavel Pukr", Edit: "Pavel Puškár", Sport: "Bobsleigh" },
  { Name: "Pavel Pukr", Edit: "Pavel Puškár", Sport: "Bobsleigh" },
  { Name: "Pavel Pukr", Edit: "Pavel Puškár", Sport: "Bobsleigh" },
  { Name: "Pavel Pukr", Edit: "Pavel Puškár", Sport: "Bobsleigh" },
  { Name: "Pavel Pukr", Edit: "Pavel Puškár", Sport: "Bobsleigh" },
  { Name: "Pavel Pukr", Edit: "Pavel Puškár", Sport: "Bobsleigh" },
  { Name: "Eva Puskarkov", Edit: "Eva Puskarčíková", Sport: "Biathlon" },
  { Name: "Eva Puskarkov", Edit: "Eva Puskarčíková", Sport: "Biathlon" },
  { Name: "Eva Puskarkov", Edit: "Eva Puskarčíková", Sport: "Biathlon" },
  { Name: "Eva Puskarkov", Edit: "Eva Puskarčíková", Sport: "Biathlon" },
  {
    Name: "Kamila Rajdlov",
    Edit: "Kamila Rajdlová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kamila Rajdlov",
    Edit: "Kamila Rajdlová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kamila Rajdlov",
    Edit: "Kamila Rajdlová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kamila Rajdlov",
    Edit: "Kamila Rajdlová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kamila Rajdlov",
    Edit: "Kamila Rajdlová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kamila Rajdlov",
    Edit: "Kamila Rajdlová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kamila Rajdlov",
    Edit: "Kamila Rajdlová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kamila Rajdlov",
    Edit: "Kamila Rajdlová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kamila Rajdlov",
    Edit: "Kamila Rajdlová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kamila Rajdlov",
    Edit: "Kamila Rajdlová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Kamila Rajdlov",
    Edit: "Kamila Rajdlová",
    Sport: "Cross Country Skiing",
  },
  { Name: "Jana Rzlov", Edit: "Jana Rázlová", Sport: "Cross Country Skiing" },
  { Name: "Jana Rzlov", Edit: "Jana Rázlová", Sport: "Cross Country Skiing" },
  { Name: "Jana Rzlov", Edit: "Jana Rázlová", Sport: "Cross Country Skiing" },
  { Name: "Ale Razm", Edit: "Aleš Razým", Sport: "Cross Country Skiing" },
  { Name: "Ale Razm", Edit: "Aleš Razým", Sport: "Cross Country Skiing" },
  { Name: "Ale Razm", Edit: "Aleš Razým", Sport: "Cross Country Skiing" },
  { Name: "Ale Razm", Edit: "Aleš Razým", Sport: "Cross Country Skiing" },
  { Name: "Radek echka", Edit: "Radek Řechka", Sport: "Bobsleigh" },
  { Name: "Robert Reichel", Edit: "Robert Reichel", Sport: "Ice Hockey" },
  { Name: "Robert Reichel", Edit: "Robert Reichel", Sport: "Ice Hockey" },
  { Name: "Magda Rezlerov", Edit: "Magda Rezlerová", Sport: "Biathlon" },
  { Name: "Magda Rezlerov", Edit: "Magda Rezlerová", Sport: "Biathlon" },
  { Name: "Magda Rezlerov", Edit: "Magda Rezlerová", Sport: "Biathlon" },
  { Name: "Magda Rezlerov", Edit: "Magda Rezlerová", Sport: "Biathlon" },
  { Name: "Magda Rezlerov", Edit: "Magda Rezlerová", Sport: "Biathlon" },
  { Name: "Magda Rezlerov", Edit: "Magda Rezlerová", Sport: "Biathlon" },
  { Name: "Magda Rezlerov", Edit: "Magda Rezlerová", Sport: "Biathlon" },
  { Name: "Magda Rezlerov", Edit: "Magda Rezlerová", Sport: "Biathlon" },
  { Name: "Magda Rezlerov", Edit: "Magda Rezlerová", Sport: "Biathlon" },
  { Name: "Magda Rezlerov", Edit: "Magda Rezlerová", Sport: "Biathlon" },
  { Name: "Tom Rolinek", Edit: "Tomáš Rolinek", Sport: "Ice Hockey" },
  { Name: "Michal Rozsval", Edit: "Michal Rozsíval", Sport: "Ice Hockey" },
  { Name: "Martin Ruinsk", Edit: "Martin Ručinský", Sport: "Ice Hockey" },
  { Name: "Martin Ruinsk", Edit: "Martin Ručinský", Sport: "Ice Hockey" },
  { Name: "Martin Ruinsk", Edit: "Martin Ručinský", Sport: "Ice Hockey" },
  { Name: "Vladimr Rika", Edit: "Vladimír Růžička", Sport: "Ice Hockey" },
  { Name: "Ladislav Rygl", Edit: "Ladislav Rygl", Sport: "Nordic Combined" },
  { Name: "Ladislav Rygl", Edit: "Ladislav Rygl", Sport: "Nordic Combined" },
  { Name: "Ladislav Rygl", Edit: "Ladislav Rygl", Sport: "Nordic Combined" },
  { Name: "Ladislav Rygl", Edit: "Ladislav Rygl", Sport: "Nordic Combined" },
  { Name: "Ladislav Rygl", Edit: "Ladislav Rygl", Sport: "Nordic Combined" },
  { Name: "Ladislav Rygl", Edit: "Ladislav Rygl", Sport: "Nordic Combined" },
  { Name: "Martina Sblkov", Edit: "Martina Sáblíková", Sport: "Speed Skating" },
  { Name: "Martina Sblkov", Edit: "Martina Sáblíková", Sport: "Speed Skating" },
  { Name: "Martina Sblkov", Edit: "Martina Sáblíková", Sport: "Speed Skating" },
  { Name: "Martina Sblkov", Edit: "Martina Sáblíková", Sport: "Speed Skating" },
  { Name: "Martina Sblkov", Edit: "Martina Sáblíková", Sport: "Speed Skating" },
  { Name: "Martina Sblkov", Edit: "Martina Sáblíková", Sport: "Speed Skating" },
  { Name: "Martina Sblkov", Edit: "Martina Sáblíková", Sport: "Speed Skating" },
  { Name: "Zdenk af", Edit: "Zdeněk Šafář", Sport: "Freestyle Skiing" },
  { Name: "Jaroslav Sakala", Edit: "Jaroslav Sakala", Sport: "Ski Jumping" },
  { Name: "Jaroslav Sakala", Edit: "Jaroslav Sakala", Sport: "Ski Jumping" },
  { Name: "Jaroslav Sakala", Edit: "Jaroslav Sakala", Sport: "Ski Jumping" },
  { Name: "Jaroslav Sakala", Edit: "Jaroslav Sakala", Sport: "Ski Jumping" },
  { Name: "Jaroslav Sakala", Edit: "Jaroslav Sakala", Sport: "Ski Jumping" },
  { Name: "Jaroslav Sakala", Edit: "Jaroslav Sakala", Sport: "Ski Jumping" },
  { Name: "Alexander Salk", Edit: "Alexander Salák", Sport: "Ice Hockey" },
  { Name: "Jana aldov", Edit: "Jana Šaldová", Sport: "Cross Country Skiing" },
  { Name: "Jana aldov", Edit: "Jana Šaldová", Sport: "Cross Country Skiing" },
  { Name: "Jana aldov", Edit: "Jana Šaldová", Sport: "Cross Country Skiing" },
  { Name: "Eva Samkov", Edit: "Eva Samková", Sport: "Snowboarding" },
  { Name: "Bedich erban", Edit: "Bedřich Ščerban", Sport: "Ice Hockey" },
  { Name: "Boivoj ", Edit: "Vlastibor Sedlák", Sport: "Ski Jumping" },
  { Name: "Boivoj ", Edit: "Borek Sedlák", Sport: "Ski Jumping" },
  { Name: "Boivoj ", Edit: "Borek Sedlák", Sport: "Ski Jumping" },
  { Name: "Martin imeek", Edit: "Martin Šimeček", Sport: "Figure Skating" },
  { Name: "Martin imeek", Edit: "Martin Šimeček", Sport: "Figure Skating" },
  { Name: "Petr indel", Edit: "Petr Šindelář", Sport: "Snowboarding" },
  { Name: "Marek Skla", Edit: "Marek Skála", Sport: "Freestyle Skiing" },
  {
    Name: "Eva Skalnkov",
    Edit: "Eva Skalníková",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Eva Skalnkov",
    Edit: "Eva Skalníková",
    Sport: "Cross Country Skiing",
  },
  { Name: "Martin koula", Edit: "Martin Škoula", Sport: "Ice Hockey" },
  { Name: "Tom Slavk", Edit: "Tomáš Slavík", Sport: "Nordic Combined" },
  { Name: "Tom Slavk", Edit: "Tomáš Slavík", Sport: "Nordic Combined" },
  { Name: "Tom Slavk", Edit: "Tomáš Slavík", Sport: "Nordic Combined" },
  { Name: "Tom Slavk", Edit: "Tomáš Slavík", Sport: "Nordic Combined" },
  { Name: "Tom Slavk", Edit: "Tomáš Slavík", Sport: "Nordic Combined" },
  { Name: "Tom Slavk", Edit: "Tomáš Slavík", Sport: "Nordic Combined" },
  { Name: "Tom Slavk", Edit: "Tomáš Slavík", Sport: "Nordic Combined" },
  { Name: "Tom Slavk", Edit: "Tomáš Slavík", Sport: "Nordic Combined" },
  { Name: "Tom Slavk", Edit: "Tomáš Slavík", Sport: "Nordic Combined" },
  { Name: "Ji lgr (Bubla-)", Edit: "Jiří Šlégr (Bubla)", Sport: "Ice Hockey" },
  { Name: "Michal lesingr", Edit: "Michal Šlesingr", Sport: "Biathlon" },
  { Name: "Michal lesingr", Edit: "Michal Šlesingr", Sport: "Biathlon" },
  { Name: "Michal lesingr", Edit: "Michal Šlesingr", Sport: "Biathlon" },
  { Name: "Michal lesingr", Edit: "Michal Šlesingr", Sport: "Biathlon" },
  { Name: "Michal lesingr", Edit: "Michal Šlesingr", Sport: "Biathlon" },
  { Name: "Michal lesingr", Edit: "Michal Šlesingr", Sport: "Biathlon" },
  { Name: "Michal lesingr", Edit: "Michal Šlesingr", Sport: "Biathlon" },
  { Name: "Michal lesingr", Edit: "Michal Šlesingr", Sport: "Biathlon" },
  { Name: "Michal lesingr", Edit: "Michal Šlesingr", Sport: "Biathlon" },
  { Name: "Michal lesingr", Edit: "Michal Šlesingr", Sport: "Biathlon" },
  { Name: "Michal lesingr", Edit: "Michal Šlesingr", Sport: "Biathlon" },
  { Name: "Richard mehlk", Edit: "Richard Šmehlík", Sport: "Ice Hockey" },
  { Name: "Richard mehlk", Edit: "Richard Šmehlík", Sport: "Ice Hockey" },
  { Name: "Petr mejc", Edit: "Petr Šmejc", Sport: "Nordic Combined" },
  { Name: "Petr mejc", Edit: "Petr Šmejc", Sport: "Nordic Combined" },
  { Name: "Petr mejc", Edit: "Petr Šmejc", Sport: "Nordic Combined" },
  { Name: "Petr mejc", Edit: "Petr Šmejc", Sport: "Nordic Combined" },
  { Name: "Ladislav md", Edit: "Ladislav Šmíd", Sport: "Ice Hockey" },
  {
    Name: "Gabriela Soukalov (-Koukalov)",
    Edit: "Gabriela Soukalová (Koukalová)",
    Sport: "Biathlon",
  },
  {
    Name: "Gabriela Soukalov (-Koukalov)",
    Edit: "Gabriela Soukalová (Koukalová)",
    Sport: "Biathlon",
  },
  {
    Name: "Gabriela Soukalov (-Koukalov)",
    Edit: "Gabriela Soukalová (Koukalová)",
    Sport: "Biathlon",
  },
  {
    Name: "Gabriela Soukalov (-Koukalov)",
    Edit: "Gabriela Soukalová (Koukalová)",
    Sport: "Biathlon",
  },
  {
    Name: "Gabriela Soukalov (-Koukalov)",
    Edit: "Gabriela Soukalová (Koukalová)",
    Sport: "Biathlon",
  },
  {
    Name: "Gabriela Soukalov (-Koukalov)",
    Edit: "Gabriela Soukalová (Koukalová)",
    Sport: "Biathlon",
  },
  {
    Name: "Gabriela Soukalov (-Koukalov)",
    Edit: "Gabriela Soukalová (Koukalová)",
    Sport: "Biathlon",
  },
  {
    Name: "Gabriela Soukalov (-Koukalov)",
    Edit: "Gabriela Soukalová (Koukalová)",
    Sport: "Biathlon",
  },
  { Name: "Jaroslav Soukup", Edit: "Jaroslav Soukup", Sport: "Biathlon" },
  { Name: "Jaroslav Soukup", Edit: "Jaroslav Soukup", Sport: "Biathlon" },
  { Name: "Jaroslav Soukup", Edit: "Jaroslav Soukup", Sport: "Biathlon" },
  { Name: "Jaroslav Soukup", Edit: "Jaroslav Soukup", Sport: "Biathlon" },
  { Name: "Jaroslav Soukup", Edit: "Jaroslav Soukup", Sport: "Biathlon" },
  { Name: "Jaroslav Soukup", Edit: "Jaroslav Soukup", Sport: "Biathlon" },
  { Name: "Jaroslav Soukup", Edit: "Jaroslav Soukup", Sport: "Biathlon" },
  { Name: "Jaroslav Soukup", Edit: "Jaroslav Soukup", Sport: "Biathlon" },
  { Name: "Jaroslav Soukup", Edit: "Jaroslav Soukup", Sport: "Biathlon" },
  { Name: "Jaroslav Soukup", Edit: "Jaroslav Soukup", Sport: "Biathlon" },
  { Name: "Jaroslav paek", Edit: "Jaroslav Špaček", Sport: "Ice Hockey" },
  { Name: "Jaroslav paek", Edit: "Jaroslav Špaček", Sport: "Ice Hockey" },
  { Name: "Jaroslav paek", Edit: "Jaroslav Špaček", Sport: "Ice Hockey" },
  { Name: "Milan perl", Edit: "Milan Šperl", Sport: "Cross Country Skiing" },
  { Name: "Milan perl", Edit: "Milan Šperl", Sport: "Cross Country Skiing" },
  { Name: "Milan perl", Edit: "Milan Šperl", Sport: "Cross Country Skiing" },
  { Name: "Milan perl", Edit: "Milan Šperl", Sport: "Cross Country Skiing" },
  { Name: "Milan perl", Edit: "Milan Šperl", Sport: "Cross Country Skiing" },
  { Name: "Milan perl", Edit: "Milan Šperl", Sport: "Cross Country Skiing" },
  { Name: "Tom Sre", Edit: "Tomáš Sršeň", Sport: "Ice Hockey" },
  { Name: "Antonn Stavjaa", Edit: "Antonín Stavjaňa", Sport: "Ice Hockey" },
  { Name: "Jan Stoklska", Edit: "Jan Stokláska", Sport: "Bobsleigh" },
  { Name: "Jan Stoklska", Edit: "Jan Stokláska", Sport: "Bobsleigh" },
  { Name: "Martin Straka", Edit: "Martin Straka", Sport: "Ice Hockey" },
  { Name: "Martin Straka", Edit: "Martin Straka", Sport: "Ice Hockey" },
  { Name: "Milan Studnika", Edit: "Milan Studnička", Sport: "Bobsleigh" },
  { Name: "Jakub Suchek", Edit: "Jakub Sucháček", Sport: "Ski Jumping" },
  { Name: "Jakub Suchek", Edit: "Jakub Sucháček", Sport: "Ski Jumping" },
  { Name: "Jakub Suchek", Edit: "Jakub Sucháček", Sport: "Ski Jumping" },
  { Name: "Dominik Such", Edit: "Dominik Suchý", Sport: "Bobsleigh" },
  { Name: "Dominik Such", Edit: "Dominik Suchý", Sport: "Bobsleigh" },
  { Name: "Nikola Sudov", Edit: "Nikola Sudová", Sport: "Freestyle Skiing" },
  { Name: "Nikola Sudov", Edit: "Nikola Sudová", Sport: "Freestyle Skiing" },
  { Name: "Nikola Sudov", Edit: "Nikola Sudová", Sport: "Freestyle Skiing" },
  { Name: "Nikola Sudov", Edit: "Nikola Sudová", Sport: "Freestyle Skiing" },
  { Name: "rka Sudov", Edit: "Šárka Sudová", Sport: "Freestyle Skiing" },
  { Name: "rka Sudov", Edit: "Šárka Sudová", Sport: "Freestyle Skiing" },
  {
    Name: "Gabriela Suvov (-Lehk)",
    Edit: "Gabriela Sůvová (Lehká)",
    Sport: "Biathlon",
  },
  { Name: "Petr Svoboda", Edit: "Petr Svoboda", Sport: "Ice Hockey" },
  { Name: "Michal Skora", Edit: "Michal Sýkora", Sport: "Ice Hockey" },
  { Name: "Petr Skora", Edit: "Petr Sýkora", Sport: "Ice Hockey" },
  { Name: "David Szurman", Edit: "David Szurman", Sport: "Figure Skating" },
  { Name: "Ji Tepl", Edit: "Jiří Teplý", Sport: "Cross Country Skiing" },
  { Name: "Ji Tepl", Edit: "Jiří Teplý", Sport: "Cross Country Skiing" },
  { Name: "Radek oupal", Edit: "Radek Ťoupal", Sport: "Ice Hockey" },
  { Name: "Filip Trejbal", Edit: "Filip Trejbal", Sport: "Alpine Skiing" },
  { Name: "Filip Trejbal", Edit: "Filip Trejbal", Sport: "Alpine Skiing" },
  { Name: "Filip Trejbal", Edit: "Filip Trejbal", Sport: "Alpine Skiing" },
  { Name: "Filip Trejbal", Edit: "Filip Trejbal", Sport: "Alpine Skiing" },
  { Name: "Filip Trejbal", Edit: "Filip Trejbal", Sport: "Alpine Skiing" },
  { Name: "Filip Trejbal", Edit: "Filip Trejbal", Sport: "Alpine Skiing" },
  { Name: "Filip Trejbal", Edit: "Filip Trejbal", Sport: "Alpine Skiing" },
  { Name: "Roman Turek", Edit: "Roman Turek", Sport: "Ice Hockey" },
  { Name: "Albta Ukolov", Edit: "Alžběta Ukolová", Sport: "Figure Skating" },
  { Name: "Michal Vacek", Edit: "Michal Vacek", Sport: "Bobsleigh" },
  { Name: "Michal Vacek", Edit: "Michal Vacek", Sport: "Bobsleigh" },
  { Name: "Luk Vaculk", Edit: "Lukáš Vaculík", Sport: "Freestyle Skiing" },
  { Name: "Ondej Vaculk", Edit: "Ondřej Vaculík", Sport: "Ski Jumping" },
  { Name: "Ondej Vaculk", Edit: "Ondřej Vaculík", Sport: "Ski Jumping" },
  {
    Name: "Tereza Vaculkov",
    Edit: "Tereza Vaculíková",
    Sport: "Freestyle Skiing",
  },
  {
    Name: "Tereza Vaculkov",
    Edit: "Tereza Vaculíková",
    Sport: "Freestyle Skiing",
  },
  { Name: "Ale Valenta", Edit: "Aleš Valenta", Sport: "Freestyle Skiing" },
  { Name: "Ale Valenta", Edit: "Aleš Valenta", Sport: "Freestyle Skiing" },
  { Name: "Ale Valenta", Edit: "Aleš Valenta", Sport: "Freestyle Skiing" },
  {
    Name: "Ondrej Valenta",
    Edit: "Ondřej Valenta",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Ondrej Valenta",
    Edit: "Ondřej Valenta",
    Sport: "Cross Country Skiing",
  },
  { Name: "Josef Vaek", Edit: "Josef Vašíček", Sport: "Ice Hockey" },
  { Name: "Ji Veber", Edit: "Jiří Veber", Sport: "Ice Hockey" },
  { Name: "Zdeka Vejnarov", Edit: "Zdeňka Vejnarová", Sport: "Biathlon" },
  { Name: "Zdeka Vejnarov", Edit: "Zdeňka Vejnarová", Sport: "Biathlon" },
  { Name: "Zdeka Vejnarov", Edit: "Zdeňka Vejnarová", Sport: "Biathlon" },
  { Name: "Zdeka Vejnarov", Edit: "Zdeňka Vejnarová", Sport: "Biathlon" },
  { Name: "Zdeka Vejnarov", Edit: "Zdeňka Vejnarová", Sport: "Biathlon" },
  { Name: "Zdeka Vejnarov", Edit: "Zdeňka Vejnarová", Sport: "Biathlon" },
  { Name: "Zdeka Vejnarov", Edit: "Zdeňka Vejnarová", Sport: "Biathlon" },
  { Name: "Zdeka Vejnarov", Edit: "Zdeňka Vejnarová", Sport: "Biathlon" },
  { Name: "Zdeka Vejnarov", Edit: "Zdeňka Vejnarová", Sport: "Biathlon" },
  { Name: "Tom Verner", Edit: "Tomáš Verner", Sport: "Figure Skating" },
  { Name: "Tom Verner", Edit: "Tomáš Verner", Sport: "Figure Skating" },
  { Name: "Tom Verner", Edit: "Tomáš Verner", Sport: "Figure Skating" },
  { Name: "Milo Vesel", Edit: "Miloš Veselý", Sport: "Bobsleigh" },
  { Name: "Milo Vesel", Edit: "Miloš Veselý", Sport: "Bobsleigh" },
  { Name: "David Vincour", Edit: "David Vincour", Sport: "Figure Skating" },
  { Name: "Zdenk Vtek", Edit: "Zdeněk Vítek", Sport: "Biathlon" },
  { Name: "Zdenk Vtek", Edit: "Zdeněk Vítek", Sport: "Biathlon" },
  { Name: "Zdenk Vtek", Edit: "Zdeněk Vítek", Sport: "Biathlon" },
  { Name: "Zdenk Vtek", Edit: "Zdeněk Vítek", Sport: "Biathlon" },
  { Name: "Zdenk Vtek", Edit: "Zdeněk Vítek", Sport: "Biathlon" },
  { Name: "Zdenk Vtek", Edit: "Zdeněk Vítek", Sport: "Biathlon" },
  { Name: "Zdenk Vtek", Edit: "Zdeněk Vítek", Sport: "Biathlon" },
  { Name: "Zdenk Vtek", Edit: "Zdeněk Vítek", Sport: "Biathlon" },
  { Name: "Zdenk Vtek", Edit: "Zdeněk Vítek", Sport: "Biathlon" },
  { Name: "Zdenk Vtek", Edit: "Zdeněk Vítek", Sport: "Biathlon" },
  { Name: "Zdenk Vtek", Edit: "Zdeněk Vítek", Sport: "Biathlon" },
  { Name: "Zdenk Vtek", Edit: "Zdeněk Vítek", Sport: "Biathlon" },
  { Name: "Zdenk Vtek", Edit: "Zdeněk Vítek", Sport: "Biathlon" },
  { Name: "Zdenk Vtek", Edit: "Zdeněk Vítek", Sport: "Biathlon" },
  { Name: "Zdenk Vtek", Edit: "Zdeněk Vítek", Sport: "Biathlon" },
  { Name: "Veronika Vtkov", Edit: "Veronika Vítková", Sport: "Biathlon" },
  { Name: "Veronika Vtkov", Edit: "Veronika Vítková", Sport: "Biathlon" },
  { Name: "Veronika Vtkov", Edit: "Veronika Vítková", Sport: "Biathlon" },
  { Name: "Veronika Vtkov", Edit: "Veronika Vítková", Sport: "Biathlon" },
  { Name: "Veronika Vtkov", Edit: "Veronika Vítková", Sport: "Biathlon" },
  { Name: "Veronika Vtkov", Edit: "Veronika Vítková", Sport: "Biathlon" },
  { Name: "Veronika Vtkov", Edit: "Veronika Vítková", Sport: "Biathlon" },
  { Name: "Veronika Vtkov", Edit: "Veronika Vítková", Sport: "Biathlon" },
  { Name: "Veronika Vtkov", Edit: "Veronika Vítková", Sport: "Biathlon" },
  { Name: "Veronika Vtkov", Edit: "Veronika Vítková", Sport: "Biathlon" },
  { Name: "Ale Vodselek", Edit: "Aleš Vodseďálek", Sport: "Nordic Combined" },
  { Name: "Ale Vodselek", Edit: "Aleš Vodseďálek", Sport: "Nordic Combined" },
  { Name: "Ale Vodselek", Edit: "Aleš Vodseďálek", Sport: "Nordic Combined" },
  { Name: "Ale Vodselek", Edit: "Aleš Vodseďálek", Sport: "Nordic Combined" },
  { Name: "Ale Vodselek", Edit: "Aleš Vodseďálek", Sport: "Nordic Combined" },
  { Name: "Tom Vokoun", Edit: "Tomáš Vokoun", Sport: "Ice Hockey" },
  { Name: "Tom Vokoun", Edit: "Tomáš Vokoun", Sport: "Ice Hockey" },
  {
    Name: "Martina Vondrov",
    Edit: "Martina Vondrová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martina Vondrov",
    Edit: "Martina Vondrová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martina Vondrov",
    Edit: "Martina Vondrová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martina Vondrov",
    Edit: "Martina Vondrová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Martina Vondrov",
    Edit: "Martina Vondrová",
    Sport: "Cross Country Skiing",
  },
  { Name: "Jan Vopat", Edit: "Jan Vopat", Sport: "Ice Hockey" },
  { Name: "Jakub Vorek", Edit: "Jakub Voráček", Sport: "Ice Hockey" },
  {
    Name: "Eva Vrabcov-Nvltov",
    Edit: "Eva Vrabcová Nývltová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Eva Vrabcov-Nvltov",
    Edit: "Eva Vrabcová Nývltová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Eva Vrabcov-Nvltov",
    Edit: "Eva Vrabcová Nývltová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Eva Vrabcov-Nvltov",
    Edit: "Eva Vrabcová Nývltová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Eva Vrabcov-Nvltov",
    Edit: "Eva Vrabcová Nývltová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Eva Vrabcov-Nvltov",
    Edit: "Eva Vrabcová Nývltová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Eva Vrabcov-Nvltov",
    Edit: "Eva Vrabcová Nývltová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Eva Vrabcov-Nvltov",
    Edit: "Eva Vrabcová Nývltová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Eva Vrabcov-Nvltov",
    Edit: "Eva Vrabcová Nývltová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Eva Vrabcov-Nvltov",
    Edit: "Eva Vrabcová Nývltová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Eva Vrabcov-Nvltov",
    Edit: "Eva Vrabcová Nývltová",
    Sport: "Cross Country Skiing",
  },
  { Name: "Martin Vrblk", Edit: "Martin Vráblík", Sport: "Alpine Skiing" },
  { Name: "Martin Vrblk", Edit: "Martin Vráblík", Sport: "Alpine Skiing" },
  { Name: "Martin Vrblk", Edit: "Martin Vráblík", Sport: "Alpine Skiing" },
  { Name: "Martin Vrblk", Edit: "Martin Vráblík", Sport: "Alpine Skiing" },
  { Name: "Martin Vrblk", Edit: "Martin Vráblík", Sport: "Alpine Skiing" },
  { Name: "Martin Vrblk", Edit: "Martin Vráblík", Sport: "Alpine Skiing" },
  { Name: "Martin Vrblk", Edit: "Martin Vráblík", Sport: "Alpine Skiing" },
  { Name: "Martin Vrblk", Edit: "Martin Vráblík", Sport: "Alpine Skiing" },
  { Name: "Martin Vrblk", Edit: "Martin Vráblík", Sport: "Alpine Skiing" },
  { Name: "Martin Vrblk", Edit: "Martin Vráblík", Sport: "Alpine Skiing" },
  { Name: "Martin Vrblk", Edit: "Martin Vráblík", Sport: "Alpine Skiing" },
  { Name: "Martin Vrblk", Edit: "Martin Vráblík", Sport: "Alpine Skiing" },
  { Name: "Martin Vrblk", Edit: "Martin Vráblík", Sport: "Alpine Skiing" },
  { Name: "Jan Vrba", Edit: "Jan Vrba", Sport: "Bobsleigh" },
  { Name: "Jan Vrba", Edit: "Jan Vrba", Sport: "Bobsleigh" },
  { Name: "Jan Vrba", Edit: "Jan Vrba", Sport: "Bobsleigh" },
  { Name: "David Vborn", Edit: "David Výborný", Sport: "Ice Hockey" },
  { Name: "Ji Vykoukal", Edit: "Jiří Vykoukal", Sport: "Ice Hockey" },
  {
    Name: "rka Zhrobsk-Strachov",
    Edit: "Šárka Strachová (Záhrobská)",
    Sport: "Alpine Skiing",
  },
  {
    Name: "rka Zhrobsk-Strachov",
    Edit: "Šárka Strachová (Záhrobská)",
    Sport: "Alpine Skiing",
  },
  {
    Name: "rka Zhrobsk-Strachov",
    Edit: "Šárka Strachová (Záhrobská)",
    Sport: "Alpine Skiing",
  },
  {
    Name: "rka Zhrobsk-Strachov",
    Edit: "Šárka Strachová (Záhrobská)",
    Sport: "Alpine Skiing",
  },
  {
    Name: "rka Zhrobsk-Strachov",
    Edit: "Šárka Strachová (Záhrobská)",
    Sport: "Alpine Skiing",
  },
  {
    Name: "rka Zhrobsk-Strachov",
    Edit: "Šárka Strachová (Záhrobská)",
    Sport: "Alpine Skiing",
  },
  {
    Name: "rka Zhrobsk-Strachov",
    Edit: "Šárka Strachová (Záhrobská)",
    Sport: "Alpine Skiing",
  },
  {
    Name: "rka Zhrobsk-Strachov",
    Edit: "Šárka Strachová (Záhrobská)",
    Sport: "Alpine Skiing",
  },
  {
    Name: "rka Zhrobsk-Strachov",
    Edit: "Šárka Strachová (Záhrobská)",
    Sport: "Alpine Skiing",
  },
  {
    Name: "rka Zhrobsk-Strachov",
    Edit: "Šárka Strachová (Záhrobská)",
    Sport: "Alpine Skiing",
  },
  {
    Name: "rka Zhrobsk-Strachov",
    Edit: "Šárka Strachová (Záhrobská)",
    Sport: "Alpine Skiing",
  },
  { Name: "Petr Zhrobsk", Edit: "Petr Záhrobský", Sport: "Alpine Skiing" },
  { Name: "Petr Zhrobsk", Edit: "Petr Záhrobský", Sport: "Alpine Skiing" },
  { Name: "Petr Zhrobsk", Edit: "Petr Záhrobský", Sport: "Alpine Skiing" },
  { Name: "Petr Zhrobsk", Edit: "Petr Záhrobský", Sport: "Alpine Skiing" },
  { Name: "Petr Zhrobsk", Edit: "Petr Záhrobský", Sport: "Alpine Skiing" },
  { Name: "Petr Zhrobsk", Edit: "Petr Záhrobský", Sport: "Alpine Skiing" },
  { Name: "Petr Zhrobsk", Edit: "Petr Záhrobský", Sport: "Alpine Skiing" },
  { Name: "Boris ", Edit: "Boris Zakouřil", Sport: "Alpine Skiing" },
  { Name: "Boris ", Edit: "Boris Zakouřil", Sport: "Alpine Skiing" },
  { Name: "Boris ", Edit: "Boris Zakouřil", Sport: "Alpine Skiing" },
  { Name: "Boris ", Edit: "Boris Zakouřil", Sport: "Alpine Skiing" },
  { Name: "Boris ", Edit: "Boris Zakouřil", Sport: "Alpine Skiing" },
  {
    Name: "Petra Zakouilov",
    Edit: "Petra Zakouřilová",
    Sport: "Alpine Skiing",
  },
  {
    Name: "Petra Zakouilov",
    Edit: "Petra Zakouřilová",
    Sport: "Alpine Skiing",
  },
  {
    Name: "Petra Zakouilov",
    Edit: "Petra Zakouřilová",
    Sport: "Alpine Skiing",
  },
  {
    Name: "Petra Zakouilov",
    Edit: "Petra Zakouřilová",
    Sport: "Alpine Skiing",
  },
  {
    Name: "Petra Zakouilov",
    Edit: "Petra Zakouřilová",
    Sport: "Alpine Skiing",
  },
  {
    Name: "Petra Zakouilov",
    Edit: "Petra Zakouřilová",
    Sport: "Alpine Skiing",
  },
  {
    Name: "Petra Zakouilov",
    Edit: "Petra Zakouřilová",
    Sport: "Alpine Skiing",
  },
  {
    Name: "Petra Zakouilov",
    Edit: "Petra Zakouřilová",
    Sport: "Alpine Skiing",
  },
  {
    Name: "Iveta Zelingerov-Fortov",
    Edit: "Iveta Fořtová-Zelingerová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Iveta Zelingerov-Fortov",
    Edit: "Iveta Fořtová-Zelingerová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Iveta Zelingerov-Fortov",
    Edit: "Iveta Fořtová-Zelingerová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Iveta Zelingerov-Fortov",
    Edit: "Iveta Fořtová-Zelingerová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Iveta Zelingerov-Fortov",
    Edit: "Iveta Fořtová-Zelingerová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Iveta Zelingerov-Fortov",
    Edit: "Iveta Fořtová-Zelingerová",
    Sport: "Cross Country Skiing",
  },
  {
    Name: "Andrea Zemanov",
    Edit: "Andrea Zemanová",
    Sport: "Freestyle Skiing",
  },
  { Name: "Irena Zemanov", Edit: "Irena Zemanová", Sport: "Figure Skating" },
  { Name: "Richard emlika", Edit: "Richard Žemlička", Sport: "Ice Hockey" },
  { Name: "Marek idlick", Edit: "Marek Židlický", Sport: "Ice Hockey" },
  { Name: "Marek idlick", Edit: "Marek Židlický", Sport: "Ice Hockey" },
  { Name: "Marek idlick", Edit: "Marek Židlický", Sport: "Ice Hockey" },
  { Name: "Veronika Zvaiov", Edit: "Veronika Zvařičová", Sport: "Biathlon" },
];

export default diakritika;
