const preklad = [
  { term: "Speed Skating", auto: "Rychlobruslení", edit: "Rychlobruslení" },
  {
    term: "Cross Country Skiing",
    auto: "Běh na lyžích",
    edit: "Běh na lyžích",
  },
  { term: "Ice Hockey", auto: "Lední hokej", edit: "Lední hokej" },
  { term: "Biathlon", auto: "Biatlon.", edit: "Biatlon" },
  { term: "Alpine Skiing", auto: "Alpské lyžování", edit: "Alpské lyžování" },
  { term: "Luge", auto: "Luge.", edit: "Saně" },
  { term: "Bobsleigh", auto: "Bobový", edit: "Boby" },
  { term: "Figure Skating", auto: "Krasobruslení", edit: "Krasobruslení" },
  {
    term: "Nordic Combined",
    auto: "Nordic kombinovaný",
    edit: "Severská kombinace",
  },
  {
    term: "Freestyle Skiing",
    auto: "Lyžování volným stylem",
    edit: "Akrobatické lyžování",
  },
  { term: "Ski Jumping", auto: "Skoky na lyžích", edit: "Skoky na lyžích" },
  { term: "Curling", auto: "Curling", edit: "Curling" },
  { term: "Snowboarding", auto: "Snowboarding", edit: "Snowboarding" },
  {
    term: "Short Track Speed Skating",
    auto: "Krátké otáčky rychlé bruslení",
    edit: "Short track",
  },
  { term: "Skeleton", auto: "Kostra", edit: "Skeleton" },
  {
    term: "Military Ski Patrol",
    auto: "Vojenská lyžařská hlídka",
    edit: "Závod vojenských hlídek",
  },
  { term: "Alpinism", auto: "Alpinismus", edit: "Alpinismus" },
  { term: "Netherlands", auto: "Holandsko", edit: "Nizozemsko" },
  { term: "United States", auto: "Spojené státy", edit: "Spojené státy" },
  { term: "Finland", auto: "Finsko", edit: "Finsko" },
  { term: "Norway", auto: "Norsko", edit: "Norsko" },
  { term: "Estonia", auto: "Estonsko", edit: "Estonsko" },
  { term: "Pakistan", auto: "Pákistán", edit: "Pákistán" },
  { term: "Iran", auto: "Írán", edit: "Írán" },
  { term: "Italy", auto: "Itálie", edit: "Itálie" },
  { term: "Japan-1", auto: "Japonsko-1.", edit: "Japonsko" },
  { term: "Japan", auto: "Japonsko", edit: "Japonsko" },
  { term: "Canada", auto: "Kanada", edit: "Kanada" },
  { term: "West Germany", auto: "západní Německo", edit: "Západní Německo" },
  { term: "Argentina", auto: "Argentina", edit: "Argentina" },
  { term: "Sweden", auto: "Švédsko", edit: "Švédsko" },
  {
    term: "United States Virgin Islands",
    auto: "Spojené státy Panenské ostrovy",
    edit: "Americké Panenské ostrovy",
  },
  { term: "Switzerland", auto: "Švýcarsko", edit: "Švýcarsko" },
  { term: "France-1", auto: "Francie-1.", edit: "Francie" },
  { term: "Ukraine", auto: "Ukrajina", edit: "Ukrajina" },
  { term: "Latvia", auto: "Lotyšsko", edit: "Lotyšsko" },
  { term: "Spain", auto: "Španělsko", edit: "Španělsko" },
  { term: "Lebanon", auto: "Libanon", edit: "Libanon" },
  { term: "Georgia", auto: "Gruzie", edit: "Gruzie" },
  { term: "Belarus", auto: "Bělorusko", edit: "Bělorusko" },
  { term: "Russia", auto: "Rusko", edit: "Rusko" },
  { term: "Croatia", auto: "Chorvatsko", edit: "Chorvatsko" },
  { term: "Russia-2", auto: "Rusko-2.", edit: "Rusko" },
  { term: "Russia-1", auto: "Rusko-1", edit: "Rusko" },
  { term: "Bulgaria", auto: "Bulharsko", edit: "Bulharsko" },
  { term: "Germany", auto: "Německo", edit: "Německo" },
  { term: "Poland", auto: "Polsko", edit: "Polsko" },
  { term: "France-2", auto: "Francie-2.", edit: "Francie" },
  { term: "Romania", auto: "Rumunsko", edit: "Rumunsko" },
  { term: "Soviet Union", auto: "Sovětský svaz", edit: "Sovětský svaz" },
  { term: "Switzerland-2", auto: "Švýcarsko-2.", edit: "Švýcarsko" },
  { term: "Switzerland-1", auto: "Švýcarsko-1.", edit: "Švýcarsko" },
  { term: "Australia", auto: "Austrálie", edit: "Austrálie" },
  { term: "Great Britain-1", auto: "Velká Británie-1", edit: "Velká Británie" },
  { term: "Czechoslovakia", auto: "Československo", edit: "Československo" },
  { term: "Czech Republic", auto: "Česká republika", edit: "Česká republika" },
  { term: "Great Britain", auto: "Velká Británie", edit: "Velká Británie" },
  { term: "East Germany", auto: "Východní Německo", edit: "Východní Německo" },
  { term: "France", auto: "Francie", edit: "Francie" },
  { term: "Germany-2", auto: "Německo-2.", edit: "Německo" },
  { term: "Kazakhstan", auto: "Kazachstán", edit: "Kazachstán" },
  { term: "Belgium", auto: "Belgie", edit: "Belgie" },
  { term: "Togo", auto: "Jít", edit: "Togo" },
  { term: "Turkey", auto: "krocan", edit: "Turecko" },
  { term: "Uzbekistan", auto: "Uzbekistán", edit: "Uzbekistán" },
  { term: "Great Britain-2", auto: "Velká Británie-2", edit: "Velká Británie" },
  { term: "United States-1", auto: "Spojené státy-1", edit: "Spojené státy" },
  { term: "United States-2", auto: "Spojené státy-2", edit: "Spojené státy" },
  { term: "Argentina-2", auto: "Argentina-2.", edit: "Argentina" },
  {
    term: "Trinidad and Tobago",
    auto: "Trinidad a Tobago",
    edit: "Trinidad a Tobago",
  },
  { term: "South Korea", auto: "Jižní Korea", edit: "Jižní Korea" },
  { term: "Sweden-2", auto: "Sweden-2", edit: "Švédsko" },
  { term: "Sweden-1", auto: "Švédsko-1", edit: "Švédsko" },
  { term: "India", auto: "Indie", edit: "Indie" },
  { term: "Italy-2", auto: "Itálie-2.", edit: "Itálie" },
  { term: "Morocco", auto: "Maroko", edit: "Maroko" },
  { term: "Denmark", auto: "Dánsko", edit: "Dánsko" },
  { term: "Canada-2", auto: "Kanada-2.", edit: "Kanada" },
  { term: "Canada-1", auto: "Kanada-1", edit: "Kanada" },
  { term: "Austria", auto: "Rakousko", edit: "Rakousko" },
  { term: "Yugoslavia", auto: "Jugoslávie", edit: "Jugoslávie" },
  { term: "Soviet Union-2", auto: "Sovětský svaz-2", edit: "Sovětský svaz" },
  { term: "Soviet Union-1", auto: "Sovětský svaz-1", edit: "Sovětský svaz" },
  { term: "Monaco", auto: "Monako.", edit: "Monako" },
  { term: "Greece", auto: "Řecko", edit: "Řecko" },
  { term: "Armenia", auto: "Arménie", edit: "Arménie" },
  { term: "Unified Team", auto: "Sjednocený tým", edit: "Sjednocený tým" },
  { term: "Hungary", auto: "Maďarsko", edit: "Maďarsko" },
  { term: "Spain-1", auto: "Španělsko-1", edit: "Španělsko" },
  { term: "Mongolia", auto: "Mongolsko", edit: "Mongolsko" },
  { term: "Mexico", auto: "Mexiko", edit: "Mexiko" },
  { term: "Norway-2", auto: "Norsko-2.", edit: "Norsko" },
  { term: "Norway-1", auto: "Norsko-1.", edit: "Norsko" },
  { term: "Italy-1", auto: "Itálie-1", edit: "Itálie" },
  { term: "Puerto Rico-2", auto: "Puerto Rico-2", edit: "Portoriko" },
  { term: "Puerto Rico", auto: "Portoriko", edit: "Portoriko" },
  { term: "North Korea", auto: "Severní Korea", edit: "Severní Korea" },
  { term: "China", auto: "Čína", edit: "Čína" },
  { term: "Germany-3", auto: "Německo-3.", edit: "Německo" },
  { term: "Romania-2", auto: "Rumunsko-2.", edit: "Rumunsko" },
  { term: "Chile", auto: "Chile", edit: "Chile" },
  { term: "Azerbaijan", auto: "Ázerbajdžán", edit: "Ázerbájdžán" },
  { term: "Soviet Union-3", auto: "Sovětský svaz-3", edit: "Sovětský svaz" },
  { term: "Andorra", auto: "Andorra", edit: "Andorra" },
  { term: "Japan-2", auto: "Japonsko-2.", edit: "Japonsko" },
  { term: "Brazil", auto: "Brazílie", edit: "Brazílie" },
  { term: "Austria-1", auto: "Rakousko-1", edit: "Rakousko" },
  { term: "Austria-2", auto: "Rakousko-2", edit: "Rakousko" },
  { term: "Bolivia", auto: "Bolívie", edit: "Bolívie" },
  { term: "Canada-3", auto: "Kanada-3.", edit: "Kanada" },
  { term: "New Zealand", auto: "Nový Zéland", edit: "Nový Zéland" },
  { term: "Lithuania", auto: "Litva.", edit: "Litva" },
  { term: "Latvia-2", auto: "Lotyšsko-2.", edit: "Lotyšsko" },
  { term: "Cyprus", auto: "Kypr", edit: "Kypr" },
  { term: "Germany-1", auto: "Německo-1", edit: "Německo" },
  { term: "Iceland", auto: "Island", edit: "Island" },
  { term: "Latvia-1", auto: "Lotyšsko-1", edit: "Lotyšsko" },
  {
    term: "West Germany-2",
    auto: "Západní Německo-2",
    edit: "Západní Německo",
  },
  { term: "Bulgaria-1", auto: "Bulharsko-1", edit: "Bulharsko" },
  { term: "Ukraine-2", auto: "Ukrajina-2.", edit: "Ukrajina" },
  { term: "Russia-3", auto: "Rusko-3.", edit: "Rusko" },
  { term: "United States-3", auto: "Spojené státy-3", edit: "Spojené státy" },
  { term: "Slovakia", auto: "Slovensko", edit: "Slovensko" },
  {
    term: "Bosnia and Herzegovina",
    auto: "Bosna a Hercegovina",
    edit: "Bosna a Hercegovina",
  },
  {
    term: "East Germany-1",
    auto: "Východ Německo-1",
    edit: "Východní Německo",
  },
  {
    term: "West Germany-1",
    auto: "Západní Německo-1",
    edit: "Západní Německo",
  },
  { term: "East Germany-2", auto: "East Germany-2", edit: "Východní Německo" },
  { term: "Moldova", auto: "Moldavsko", edit: "Moldavsko" },
  { term: "Tonga", auto: "Tonga.", edit: "Tonga" },
  { term: "Guam", auto: "Guam", edit: "Guam" },
  { term: "Ireland", auto: "Irsko", edit: "Irsko" },
  { term: "Great Britain-3", auto: "Velká Británie-3", edit: "Velká Británie" },
  {
    term: "Czechoslovakia-1",
    auto: "Československo-1",
    edit: "Československo",
  },
  {
    term: "Czechoslovakia-2",
    auto: "Československo-2.",
    edit: "Československo",
  },
  { term: "San Marino", auto: "San Marino", edit: "San Marino" },
  { term: "Spain-2", auto: "Španělsko-2.", edit: "Španělsko" },
  { term: "Slovenia", auto: "Slovinsko", edit: "Slovinsko" },
  { term: "Unified Team-2", auto: "Unified Team-2", edit: "Sjednocený tým" },
  { term: "Liechtenstein", auto: "Lichtenštejnsko", edit: "Lichtenštejnsko" },
  { term: "Israel-2", auto: "Izrael-2", edit: "Izrael" },
  { term: "Algeria", auto: "Alžírsko", edit: "Alžírsko" },
  { term: "Romania-1", auto: "Rumunsko-1", edit: "Rumunsko" },
  { term: "Portugal", auto: "Portugalsko", edit: "Portugalsko" },
  { term: "Italy-3", auto: "Itálie-3.", edit: "Itálie" },
  { term: "Monaco-1", auto: "MONACO-1", edit: "Monako" },
  { term: "Chinese Taipei", auto: "Čínský Taipei.", edit: "Čínská Tchaj-pej" },
  { term: "Venezuela", auto: "Venezuela", edit: "Venezuela" },
  { term: "Puerto Rico-1", auto: "Puerto Rico-1", edit: "Portoriko" },
  {
    term: "Czech Republic-2",
    auto: "Česká republika-2",
    edit: "Česká republika",
  },
  { term: "Kenya", auto: "Keňa", edit: "Keňa" },
  { term: "Kyrgyzstan", auto: "Kyrgyzstán", edit: "Kyrgyzstán" },
  { term: "Unified Team-1", auto: "Jednotný tým-1", edit: "Sjednocený tým" },
  { term: "Bulgaria-2", auto: "Bulharsko-2.", edit: "Bulharsko" },
  { term: "South Africa", auto: "Jižní Afrika", edit: "Jižní Afrika" },
  { term: "Belgium-1", auto: "BELGIE-1", edit: "Belgie" },
  { term: "Netherlands-2", auto: "NIZOZEMSKO-2", edit: "Nizozemsko" },
  { term: "Netherlands-1", auto: "NIZOZEMSKO-1", edit: "Nizozemsko" },
  { term: "Jamaica", auto: "Jamaica", edit: "Jamajka" },
  { term: "Guatemala", auto: "Guatemala", edit: "Guatemala" },
  { term: "Montenegro", auto: "Černá Hora", edit: "Černá Hora" },
  { term: "Serbia", auto: "Srbsko", edit: "Srbsko" },
  { term: "Nepal", auto: "Nepál", edit: "Nepál" },
  {
    term: "United States Virgin Islands-2",
    auto: "Spojené státy Panenské ostrovy-2",
    edit: "Americké Panenské ostrovy",
  },
  {
    term: "United States Virgin Islands-1",
    auto: "Spojené státy Panenské ostrovy-1",
    edit: "Americké Panenské ostrovy",
  },
  { term: "Israel", auto: "Izrael", edit: "Izrael" },
  { term: "Monaco-2", auto: "MONACO-2", edit: "Monako" },
  { term: "Costa Rica", auto: "Kostarika", edit: "Kostarika" },
  { term: "Peru", auto: "Peru", edit: "Peru" },
  {
    term: "Netherlands Antilles",
    auto: "Nizozemské Antily",
    edit: "Nizozemské Antily",
  },
  { term: "Mexico-2", auto: "Mexiko-2.", edit: "Mexiko" },
  { term: "Israel-1", auto: "Izrael-1", edit: "Izrael" },
  {
    term: "Chinese Taipei-1",
    auto: "Čínský Taipei-1",
    edit: "Čínská Tchaj-pej",
  },
  {
    term: "Chinese Taipei-2",
    auto: "Čínský Taipei-2",
    edit: "Čínská Tchaj-pej",
  },
  { term: "Poland-2", auto: "Polsko-2.", edit: "Polsko" },
  { term: "Poland-1", auto: "Polsko-1", edit: "Polsko" },
  { term: "Philippines", auto: "Filipíny", edit: "Filipíny" },
  {
    term: "British Virgin Islands",
    auto: "Britské Panenské ostrovy",
    edit: "Britské Panenské ostrovy",
  },
  { term: "Macedonia", auto: "Makedonie", edit: "Makedonie" },
  {
    term: "Czech Republic-1",
    auto: "Česká republika-1",
    edit: "Česká republika",
  },
  { term: "Argentina-1", auto: "Argentina-1", edit: "Argentina" },
  { term: "Belgium-2", auto: "Belgie-2.", edit: "Belgie" },
  { term: "France-3", auto: "Francie-3.", edit: "Francie" },
  { term: "Colombia", auto: "Kolumbie", edit: "Kolumbie" },
  { term: "Australia-1", auto: "Austrálie-1", edit: "Austrálie" },
  { term: "Dominica", auto: "Dominika", edit: "Dominika" },
  { term: "Ireland-2", auto: "Irsko-2.", edit: "Irsko" },
  {
    term: "Serbia and Montenegro",
    auto: "Srbsko a Černá Hora",
    edit: "Srbsko a Černá Hora",
  },
  { term: "Tajikistan", auto: "Tádžikistán", edit: "Tádžikistán" },
  { term: "Egypt", auto: "Egypt", edit: "Egypt" },
  { term: "Mexico-1", auto: "Mexiko-1", edit: "Mexiko" },
  { term: "Hungary-1", auto: "Maďarsko-1.", edit: "Maďarsko" },
  { term: "Yugoslavia-1", auto: "Jugoslávie-1", edit: "Jugoslávie" },
  { term: "Swaziland", auto: "Svazijsko", edit: "Svazijsko" },
  { term: "Luxembourg", auto: "Lucembursko", edit: "Lucembursko" },
  { term: "Senegal", auto: "Senegal.", edit: "Senegal" },
  { term: "Timor Leste", auto: "Timor Leste.", edit: "Východní Timor" },
  { term: "Unified Team-3", auto: "Unified Team-3", edit: "Sjednocený tým" },
  { term: "Ukraine-1", auto: "Ukrajina-1", edit: "Ukrajina" },
  { term: "Hong Kong", auto: "Hongkong", edit: "Hongkong" },
  { term: "Australia-2", auto: "Austrálie-2", edit: "Austrálie" },
  { term: "Jamaica-2", auto: "Jamajka-2.", edit: "Jamajka" },
  { term: "New Zealand-1", auto: "Nový Zéland-1", edit: "Nový Zéland" },
  { term: "Uruguay", auto: "Uruguay", edit: "Uruguay" },
  { term: "Slovakia-1", auto: "Slovensko-1", edit: "Slovensko" },
  { term: "South Korea-2", auto: "Jižní Korea - 2", edit: "Jižní Korea" },
  { term: "South Korea-1", auto: "Jižní Korea - 1", edit: "Jižní Korea" },
  { term: "Yugoslavia-2", auto: "Jugoslávie-2", edit: "Jugoslávie" },
  { term: "East Germany-3", auto: "Východ Německo-3", edit: "Východ Německo" },
  {
    term: "Individual Olympic Athletes",
    auto: "Jednotlivé olympijské sportovci",
    edit: "Nezávislý olympionik",
  },
  { term: "American Samoa", auto: "Americká Samoa", edit: "Americká Samoa" },
  { term: "Luxembourg-2", auto: "Lucembursko-2.", edit: "Lucembursko" },
  { term: "Portugal-2", auto: "Portugalsko-2.", edit: "Portugalsko" },
  { term: "Paraguay", auto: "Paraguay", edit: "Paraguay" },
  { term: "Ireland-1", auto: "Irsko-1.", edit: "Irsko" },
  { term: "Albania", auto: "Albánie", edit: "Albánie" },
  { term: "Cameroon", auto: "Kamerun", edit: "Kamerun" },
  { term: "Bermuda", auto: "Bermudy", edit: "Bermudy" },
  { term: "Thailand", auto: "Thajsko", edit: "Thajsko" },
  { term: "Hungary-2", auto: "Maďarsko-2.", edit: "Maďarsko" },
  { term: "Ghana", auto: "Ghana", edit: "Ghana" },
  { term: "Uzbekistan-2", auto: "Uzbekistán-2", edit: "Uzbekistán" },
  { term: "Honduras", auto: "Honduras", edit: "Honduras" },
  { term: "China-2", auto: "Čína-2.", edit: "Čína" },
  { term: "China-1", auto: "Čína-1", edit: "Čína" },
  { term: "Malta", auto: "Malta", edit: "Malta" },
  { term: "New Zealand-2", auto: "Nový Zéland-2", edit: "Nový Zéland" },
  { term: "Portugal-1", auto: "Portugalsko-1", edit: "Portugalsko" },
  { term: "Madagascar", auto: "Madagaskar", edit: "Madagaskar" },
  { term: "Uzbekistan-1", auto: "Uzbekistán-1", edit: "Uzbekistán" },
  { term: "Fiji", auto: "Fidži", edit: "Fidži" },
  { term: "China-3", auto: "Čína-3.", edit: "Čína" },
  { term: "Slovakia-2", auto: "Slovensko-2.", edit: "Slovensko" },
  { term: "Zimbabwe", auto: "Zimbabwe", edit: "Zimbabwe" },
  { term: "Jamaica-1", auto: "Jamajka-1", edit: "Jamajka" },
  {
    term: "West Germany-3",
    auto: "Západní Německo-3",
    edit: "Západní Německo",
  },
  { term: "Ethiopia", auto: "Etiopie", edit: "Etiopie" },
  {
    term: "Cayman Islands",
    auto: "Kajmanské ostrovy",
    edit: "Kajmanské ostrovy",
  },
  { term: "Luxembourg-1", auto: "Lucembursko-1", edit: "Lucembursko" },
  { term: "Chamonix", auto: "Chamonix.", edit: "Chamonix." },
  { term: "Sankt Moritz", auto: "Sankt Moritz.", edit: "Svatý Mořic" },
  { term: "Lake Placid", auto: "Jezero placid", edit: "Lake Placid" },
  {
    term: "Garmisch-Partenkirchen",
    auto: "Garmisch-Partenkirchen.",
    edit: "Garmisch-Partenkirchen",
  },
  { term: "Sankt Moritz", auto: "Sankt Moritz.", edit: "Svatý Mořic" },
  { term: "Oslo", auto: "Oslo", edit: "Oslo" },
  {
    term: "Cortina d'Ampezzo",
    auto: "Cortina d'Ampezzo.",
    edit: "Cortina d'Ampezzo",
  },
  { term: "Squaw Valley", auto: "Squaw Valley.", edit: "Squaw Valley" },
  { term: "Innsbruck", auto: "Innsbruck.", edit: "Innsbruck" },
  { term: "Grenoble", auto: "Grenoble", edit: "Grenoble" },
  { term: "Sapporo", auto: "Sapporo.", edit: "Sapporo" },
  { term: "Innsbruck", auto: "Innsbruck.", edit: "Innsbruck" },
  { term: "Lake Placid", auto: "Jezero placid", edit: "Lake Placid" },
  { term: "Sarajevo", auto: "Sarajevo.", edit: "Sarajevo" },
  { term: "Calgary", auto: "Calgary.", edit: "Calgary" },
  { term: "Albertville", auto: "Albertville", edit: "Albertville" },
  { term: "Lillehammer", auto: "Lillehammer", edit: "Lillehammer" },
  { term: "Nagano", auto: "Nagano", edit: "Nagano" },
  { term: "Salt Lake City", auto: "Salt Lake City.", edit: "Salt Lake City" },
  { term: "Torino", auto: "Turín", edit: "Turín" },
  { term: "Vancouver", auto: "Vancouver.", edit: "Vancouver" },
  { term: "Sochi", auto: "Soči", edit: "Soči" },
];

export default preklad;
